<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <Nullable>enable</Nullable>
    <!--    <AnalysisLevel>8</AnalysisLevel>-->
    <AnalysisLevelPerformance>latest</AnalysisLevelPerformance>
    <!--    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
    <NoWarn>$(NoWarn);SYSLIB1012</NoWarn>
  </PropertyGroup>

  <Target Name="CustomVersion" AfterTargets="MinVer">
    <PropertyGroup>
      <FileVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch)</FileVersion>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch)</AssemblyVersion>
      <PackageVersion>$(MinVerVersion)</PackageVersion>
    </PropertyGroup>
  </Target>
</Project>