<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <OpenTelemtryVersion>1.13.1</OpenTelemtryVersion>
    <BenchmarkDotNetVersion>0.14.0</BenchmarkDotNetVersion>
    <Net8Version>8.0.0</Net8Version>
    <xUnitVersion>2.9.2</xUnitVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.1"/>
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="7.0.2"/>
    <PackageVersion Include="System.IO.Pipelines" Version="7.0.0"/>
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="7.0.0"/>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0"/>
    <PackageVersion Include="Serilog.Extensions.Logging" Version="7.0.0"/>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1"/>
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="8.0.1"/>
    <PackageVersion Include="System.IO.Pipelines" Version="$(Net8Version)"/>
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(Net8Version)"/>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(Net8Version)"/>
    <PackageVersion Include="Serilog.Extensions.Logging" Version="8.0.0"/>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0"/>
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="9.0.0"/>
    <PackageVersion Include="System.IO.Pipelines" Version="9.0.0"/>
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.0"/>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.0"/>
    <PackageVersion Include="Serilog.Extensions.Logging" Version="9.0.0"/>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.15.0.120848"/>
    <PackageVersion Include="FastEnum" Version="2.0.5"/>
    <PackageVersion Include="Snappier" Version="1.2.0"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="4.14.0"/>

    <!--Tests-->
    <PackageVersion Include="NSubstitute" Version="5.3.0"/>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.0"/>
    <PackageVersion Include="xunit.v3" Version="3.1.0"/>
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
    <PackageVersion Include="xunit.skippablefact" Version="1.5.23"/>
    <PackageVersion Include="coverlet.collector" Version="6.0.4"/>
    <PackageVersion Include="FluentAssertions" Version="7.2.0"/>
    <!--OpenTelemetry-->
    <PackageVersion Include="OpenTelemetry" Version="$(OpenTelemtryVersion)"/>
    <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="$(OpenTelemtryVersion)"/>
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="$(OpenTelemtryVersion)"/>
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.13.1-beta.1"/>
    <!--Serilog-->
    <PackageVersion Include="Serilog" Version="4.3.0"/>
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0"/>
    <PackageVersion Include="Confluent.Kafka" Version="2.12.0"/>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4"/>
    <!--BenchmarkDotNet-->
    <PackageVersion Include="BenchmarkDotNet" Version="$(BenchmarkDotNetVersion)"/>
    <PackageVersion Include="BenchmarkDotNet.Diagnostics.Windows" Version="$(BenchmarkDotNetVersion)"/>
    <PackageVersion Include="MinVer" Version="6.0.0"/>
  </ItemGroup>
</Project>