namespace Microlibs.Kafka.Protocol
{
    public enum ErrorCodes: short
    {
        UnknownServerError = -0x1,
        None = 0x0,
        OffsetOutOfRange = 0x1,
        CorruptMessage = 0x2,
        UnknownTopicOrPartition = 0x3,
        InvalidFetchSize = 0x4,
        LeaderNotAvailable = 0x5,
        NotLeaderOrFollower = 0x6,
        RequestTimedOut = 0x7,
        BrokerNotAvailable = 0x8,
        ReplicaNotAvailable = 0x9,
        MessageTooLarge = 10,
        StaleControllerEpoch = 11,
        OffsetMetadataTooLarge = 12,
        NetworkException = 13,
        CoordinatorLoadInProgress = 14,
        CoordinatorNotAvailable = 15,
        NotCoordinator = 16,
        InvalidTopicException = 17,
        RecordListTooLarge = 18,
        NotEnoughReplicas = 19,
        NotEnoughReplicasAfterAppend = 20,
        InvalidRequiredAcks = 21,
        IllegalGeneration = 22,
        InconsistentGroupProtocol = 23,
        InvalidGroupId = 24,
        UnknownMemberId = 25,
        InvalidSessionTimeout = 26,
        RebalanceInProgress = 27,
        InvalidCommitOffsetSize = 28,
        TopicAuthorizationFailed = 29,
        GroupAuthorizationFailed = 30,
        ClusterAuthorizationFailed = 31,
        InvalidTimestamp = 32,
        UnsupportedSaslMechanism = 33,
        IllegalSaslState = 34,
        UnsupportedVersion = 35,
        TopicAlreadyExists = 36,
        InvalidPartitions = 37,
        InvalidReplicationFactor = 38,
        
    }
}