//FF-39-A6-AD-92-88-5E-B8-74-A7-7F-C3-F0-D6-BD-D0-17-1B-46-F5-4C-CD-5A-E5-03-B5-99-A9-BD-22-CC-86
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Exceptions;
using NKafka.Protocol;
using NKafka.Protocol.Buffers;
using NKafka.Protocol.Extensions;
using NKafka.Protocol.Records;
using System.Text;

namespace NKafka.Messages;

/// <summary>
/// Describes the contract for message AddPartitionsToTxnRequestMessage
/// </summary>
internal sealed partial class AddPartitionsToTxnRequestMessage: IRequestMessage, IEquatable<AddPartitionsToTxnRequestMessage>
{
    /// <inheritdoc />
    public ApiKeys ApiKey => ApiKeys.AddPartitionsToTxn;

    /// <summary>
    /// Indicates whether the request is accessed by any broker or only by the controller
    /// </summary>
    public const bool ONLY_CONTROLLER = false;

    /// <inheritdoc />
    public bool OnlyController => ONLY_CONTROLLER;

    /// <inheritdoc />
    public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

    /// <inheritdoc />
    public int IncomingBufferLength { get; private set; } = 0;

    /// <summary>
    /// List of transactions to add partitions to.
    /// </summary>
    public AddPartitionsToTxnTransactionCollection Transactions { get; set; } = new ();

    /// <summary>
    /// The transactional id corresponding to the transaction.
    /// </summary>
    public string V3AndBelowTransactionalId { get; set; } = string.Empty;

    /// <summary>
    /// Current producer id in use by the transactional id.
    /// </summary>
    public long V3AndBelowProducerId { get; set; } = 0;

    /// <summary>
    /// Current epoch associated with the producer id.
    /// </summary>
    public short V3AndBelowProducerEpoch { get; set; } = 0;

    /// <summary>
    /// The partitions to add to the transaction.
    /// </summary>
    public AddPartitionsToTxnTopicCollection V3AndBelowTopics { get; set; } = new ();

    /// <summary>
    /// The basic constructor of the message AddPartitionsToTxnRequestMessage
    /// </summary>
    public AddPartitionsToTxnRequestMessage()
    {
    }

    /// <summary>
    /// Base constructor for deserializing message AddPartitionsToTxnRequestMessage
    /// </summary>
    public AddPartitionsToTxnRequestMessage(ref BufferReader reader, ApiVersion version)
        : this()
    {
        IncomingBufferLength = reader.Length;
        Read(ref reader, version);
    }

    /// <inheritdoc />
    public void Read(ref BufferReader reader, ApiVersion version)
    {
        if (version >= ApiVersion.Version4)
        {
            int arrayLength;
            arrayLength = reader.ReadVarUInt32() - 1;
            if (arrayLength < 0)
            {
                throw new Exception("non-nullable field Transactions was serialized as null");
            }
            else
            {
                var newCollection = new AddPartitionsToTxnTransactionCollection(arrayLength);
                for (var i = 0; i < arrayLength; i++)
                {
                    newCollection.Add(new AddPartitionsToTxnTransactionMessage(ref reader, version));
                }
                Transactions = newCollection;
            }
        }
        else
        {
            Transactions = new ();
        }
        if (version <= ApiVersion.Version3)
        {
            int length;
            if (version >= ApiVersion.Version3)
            {
                length = reader.ReadVarUInt32() - 1;
            }
            else
            {
                length = reader.ReadShort();
            }
            if (length < 0)
            {
                throw new Exception("non-nullable field V3AndBelowTransactionalId was serialized as null");
            }
            else if (length > 0x7fff)
            {
                throw new Exception($"string field V3AndBelowTransactionalId had invalid length {length}");
            }
            else
            {
                V3AndBelowTransactionalId = reader.ReadString(length);
            }
        }
        else
        {
            V3AndBelowTransactionalId = string.Empty;
        }
        if (version <= ApiVersion.Version3)
        {
            V3AndBelowProducerId = reader.ReadLong();
        }
        else
        {
            V3AndBelowProducerId = 0;
        }
        if (version <= ApiVersion.Version3)
        {
            V3AndBelowProducerEpoch = reader.ReadShort();
        }
        else
        {
            V3AndBelowProducerEpoch = 0;
        }
        if (version <= ApiVersion.Version3)
        {
            if (version >= ApiVersion.Version3)
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field V3AndBelowTopics was serialized as null");
                }
                else
                {
                    var newCollection = new AddPartitionsToTxnTopicCollection(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new AddPartitionsToTxnTopicMessage(ref reader, version));
                    }
                    V3AndBelowTopics = newCollection;
                }
            }
            else
            {
                int arrayLength;
                arrayLength = reader.ReadInt();
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field V3AndBelowTopics was serialized as null");
                }
                else
                {
                    var newCollection = new AddPartitionsToTxnTopicCollection(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new AddPartitionsToTxnTopicMessage(ref reader, version));
                    }
                    V3AndBelowTopics = newCollection;
                }
            }
        }
        else
        {
            V3AndBelowTopics = new ();
        }
        UnknownTaggedFields = null;
        if (version >= ApiVersion.Version3)
        {
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }
    }

    /// <inheritdoc />
    public void Write(ref BufferWriter writer, ApiVersion version)
    {
        var numTaggedFields = 0;
        if (version >= ApiVersion.Version4)
        {
            writer.WriteVarUInt32(Transactions.Count + 1);
            foreach (var element in Transactions)
            {
                element?.Write(ref writer, version);
            }
        }
        else
        {
            if (Transactions.Count != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default Transactions at version {version}");
            }
        }
        if (version <= ApiVersion.Version3)
        {
            {
                if (version >= ApiVersion.Version3)
                {
                    writer.WriteCompactString(V3AndBelowTransactionalId);
                }
                else
                {
                    writer.WriteInt16String(V3AndBelowTransactionalId);
                }
            }
        }
        else
        {
            if (!V3AndBelowTransactionalId.Equals(string.Empty))
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default V3AndBelowTransactionalId at version {version}");
            }
        }
        if (version <= ApiVersion.Version3)
        {
            writer.WriteLong(V3AndBelowProducerId);
        }
        else
        {
            if (V3AndBelowProducerId != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default V3AndBelowProducerId at version {version}");
            }
        }
        if (version <= ApiVersion.Version3)
        {
            writer.WriteShort(V3AndBelowProducerEpoch);
        }
        else
        {
            if (V3AndBelowProducerEpoch != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default V3AndBelowProducerEpoch at version {version}");
            }
        }
        if (version <= ApiVersion.Version3)
        {
            if (version >= ApiVersion.Version3)
            {
                writer.WriteVarUInt32(V3AndBelowTopics.Count + 1);
                foreach (var element in V3AndBelowTopics)
                {
                    element?.Write(ref writer, version);
                }
            }
            else
            {
                writer.WriteInt(V3AndBelowTopics.Count);
                foreach (var element in V3AndBelowTopics)
                {
                    element?.Write(ref writer, version);
                }
            }
        }
        else
        {
            if (V3AndBelowTopics.Count != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default V3AndBelowTopics at version {version}");
            }
        }
        var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
        numTaggedFields += rawWriter.FieldsCount;
        if (version >= ApiVersion.Version3)
        {
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }
        else
        {
            if (numTaggedFields > 0)
            {
                throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
            }
        }
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is AddPartitionsToTxnRequestMessage other && Equals(other);
    }

    /// <inheritdoc />
    public bool Equals(AddPartitionsToTxnRequestMessage? other)
    {
        if (other is null)
        {
            return false;
        }
        if (Transactions is null)
        {
            if (other.Transactions is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Transactions.SequenceEqual(other.Transactions))
            {
                return false;
            }
        }
        if (V3AndBelowTransactionalId is null)
        {
            if (other.V3AndBelowTransactionalId is not null)
            {
                return false;
            }
        }
        else
        {
            if (!V3AndBelowTransactionalId.Equals(other.V3AndBelowTransactionalId))
            {
                return false;
            }
        }
        if (V3AndBelowProducerId != other.V3AndBelowProducerId)
        {
            return false;
        }
        if (V3AndBelowProducerEpoch != other.V3AndBelowProducerEpoch)
        {
            return false;
        }
        if (V3AndBelowTopics is null)
        {
            if (other.V3AndBelowTopics is not null)
            {
                return false;
            }
        }
        else
        {
            if (!V3AndBelowTopics.SequenceEqual(other.V3AndBelowTopics))
            {
                return false;
            }
        }
        return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hashCode = 0;
        hashCode = HashCode.Combine(hashCode, Transactions, V3AndBelowTransactionalId, V3AndBelowProducerId, V3AndBelowProducerEpoch, V3AndBelowTopics);
        return hashCode;
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return "AddPartitionsToTxnRequestMessage("
            + "Transactions=" + Transactions.DeepToString()
            + ", V3AndBelowTransactionalId=" + (string.IsNullOrWhiteSpace(V3AndBelowTransactionalId) ? "null" : V3AndBelowTransactionalId)
            + ", V3AndBelowProducerId=" + V3AndBelowProducerId
            + ", V3AndBelowProducerEpoch=" + V3AndBelowProducerEpoch
            + ", V3AndBelowTopics=" + V3AndBelowTopics.DeepToString()
            + ")";
    }

    /// <summary>
    /// Describes the contract for message AddPartitionsToTxnTransactionMessage
    /// </summary>
    internal sealed partial class AddPartitionsToTxnTransactionMessage: IMessage, IEquatable<AddPartitionsToTxnTransactionMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The transactional id corresponding to the transaction.
        /// </summary>
        public string TransactionalId { get; set; } = string.Empty;

        /// <summary>
        /// Current producer id in use by the transactional id.
        /// </summary>
        public long ProducerId { get; set; } = 0;

        /// <summary>
        /// Current epoch associated with the producer id.
        /// </summary>
        public short ProducerEpoch { get; set; } = 0;

        /// <summary>
        /// Boolean to signify if we want to check if the partition is in the transaction rather than add it.
        /// </summary>
        public bool VerifyOnly { get; set; } = false;

        /// <summary>
        /// The partitions to add to the transaction.
        /// </summary>
        public AddPartitionsToTxnTopicCollection Topics { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message AddPartitionsToTxnTransactionMessage
        /// </summary>
        public AddPartitionsToTxnTransactionMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message AddPartitionsToTxnTransactionMessage
        /// </summary>
        public AddPartitionsToTxnTransactionMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version5)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of AddPartitionsToTxnTransactionMessage");
            }
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    throw new Exception("non-nullable field TransactionalId was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field TransactionalId had invalid length {length}");
                }
                else
                {
                    TransactionalId = reader.ReadString(length);
                }
            }
            ProducerId = reader.ReadLong();
            ProducerEpoch = reader.ReadShort();
            VerifyOnly = reader.ReadByte() != 0;
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Topics was serialized as null");
                }
                else
                {
                    var newCollection = new AddPartitionsToTxnTopicCollection(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new AddPartitionsToTxnTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            if (version < ApiVersion.Version4)
            {
                throw new UnsupportedVersionException($"Can't write version {version} of AddPartitionsToTxnTransactionMessage");
            }
            var numTaggedFields = 0;
            {
                writer.WriteCompactString(TransactionalId);
            }
            writer.WriteLong(ProducerId);
            writer.WriteShort(ProducerEpoch);
            writer.WriteBool(VerifyOnly);
            writer.WriteVarUInt32(Topics.Count + 1);
            foreach (var element in Topics)
            {
                element?.Write(ref writer, version);
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is AddPartitionsToTxnTransactionMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(AddPartitionsToTxnTransactionMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (TransactionalId is null)
            {
                if (other.TransactionalId is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!TransactionalId.Equals(other.TransactionalId))
                {
                    return false;
                }
            }
            if (ProducerId != other.ProducerId)
            {
                return false;
            }
            if (ProducerEpoch != other.ProducerEpoch)
            {
                return false;
            }
            if (VerifyOnly != other.VerifyOnly)
            {
                return false;
            }
            if (Topics is null)
            {
                if (other.Topics is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Topics.SequenceEqual(other.Topics))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, TransactionalId);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "AddPartitionsToTxnTransactionMessage("
                + "TransactionalId=" + (string.IsNullOrWhiteSpace(TransactionalId) ? "null" : TransactionalId)
                + ", ProducerId=" + ProducerId
                + ", ProducerEpoch=" + ProducerEpoch
                + ", VerifyOnly=" + (VerifyOnly ? "true" : "false")
                + ", Topics=" + Topics.DeepToString()
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message AddPartitionsToTxnTransactionCollection
    /// </summary>
    internal sealed partial class AddPartitionsToTxnTransactionCollection: HashSet<AddPartitionsToTxnTransactionMessage>
    {
        /// <summary>
        /// Basic collection constructor
        /// </summary>
        public AddPartitionsToTxnTransactionCollection()
        {
        }

        /// <summary>
        /// Basic collection constructor with the ability to set capacity
        /// </summary>
        public AddPartitionsToTxnTransactionCollection(int capacity)
            : base(capacity)
        {
        }
        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return SetEquals((IEnumerable<AddPartitionsToTxnTransactionMessage>)obj);
        }
    }

    /// <summary>
    /// Describes the contract for message AddPartitionsToTxnTopicMessage
    /// </summary>
    internal sealed partial class AddPartitionsToTxnTopicMessage: IMessage, IEquatable<AddPartitionsToTxnTopicMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The name of the topic.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The partition indexes to add to the transaction.
        /// </summary>
        public List<int> Partitions { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message AddPartitionsToTxnTopicMessage
        /// </summary>
        public AddPartitionsToTxnTopicMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message AddPartitionsToTxnTopicMessage
        /// </summary>
        public AddPartitionsToTxnTopicMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version5)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of AddPartitionsToTxnTopicMessage");
            }
            {
                int length;
                if (version >= ApiVersion.Version3)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    throw new Exception("non-nullable field Name was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Name had invalid length {length}");
                }
                else
                {
                    Name = reader.ReadString(length);
                }
            }
            {
                int arrayLength;
                if (version >= ApiVersion.Version3)
                {
                    arrayLength = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    arrayLength = reader.ReadInt();
                }
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Partitions was serialized as null");
                }
                else
                {
                    var newCollection = new List<int>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(reader.ReadInt());
                    }
                    Partitions = newCollection;
                }
            }
            UnknownTaggedFields = null;
            if (version >= ApiVersion.Version3)
            {
                var numTaggedFields = reader.ReadVarInt32();
                for (var t = 0; t < numTaggedFields; t++)
                {
                    var tag = reader.ReadVarInt32();
                    var size = reader.ReadVarInt32();
                    switch (tag)
                    {
                        default:
                            UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                            break;
                    }
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            {
                if (version >= ApiVersion.Version3)
                {
                    writer.WriteCompactString(Name);
                }
                else
                {
                    writer.WriteInt16String(Name);
                }
            }
            if (version >= ApiVersion.Version3)
            {
                writer.WriteVarUInt32(Partitions.Count + 1);
            }
            else
            {
                writer.WriteInt(Partitions.Count);
            }
            foreach (var element in Partitions)
            {
                writer.WriteInt(element);
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            if (version >= ApiVersion.Version3)
            {
                writer.WriteVarUInt32(numTaggedFields);
                rawWriter.WriteRawTags(ref writer, int.MaxValue);
            }
            else
            {
                if (numTaggedFields > 0)
                {
                    throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
                }
            }
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is AddPartitionsToTxnTopicMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(AddPartitionsToTxnTopicMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (Name is null)
            {
                if (other.Name is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Name.Equals(other.Name))
                {
                    return false;
                }
            }
            if (Partitions is null)
            {
                if (other.Partitions is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Partitions.SequenceEqual(other.Partitions))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, Name);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "AddPartitionsToTxnTopicMessage("
                + "Name=" + (string.IsNullOrWhiteSpace(Name) ? "null" : Name)
                + ", Partitions=" + Partitions.DeepToString()
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message AddPartitionsToTxnTopicCollection
    /// </summary>
    internal sealed partial class AddPartitionsToTxnTopicCollection: HashSet<AddPartitionsToTxnTopicMessage>
    {
        /// <summary>
        /// Basic collection constructor
        /// </summary>
        public AddPartitionsToTxnTopicCollection()
        {
        }

        /// <summary>
        /// Basic collection constructor with the ability to set capacity
        /// </summary>
        public AddPartitionsToTxnTopicCollection(int capacity)
            : base(capacity)
        {
        }
        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return SetEquals((IEnumerable<AddPartitionsToTxnTopicMessage>)obj);
        }
    }
}
