//72-35-98-19-0D-B3-D9-16-10-16-EA-FB-F5-B5-51-13-F0-6E-EF-53-22-76-C3-3B-90-E7-D0-9F-5B-F0-B7-F3
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Exceptions;
using NKafka.Protocol;
using NKafka.Protocol.Buffers;
using NKafka.Protocol.Extensions;
using NKafka.Protocol.Records;
using System.Text;

namespace NKafka.Messages;

/// <summary>
/// Describes the contract for message FetchSnapshotResponseMessage
/// </summary>
internal sealed partial class FetchSnapshotResponseMessage: IResponseMessage, IEquatable<FetchSnapshotResponseMessage>
{
    /// <inheritdoc />
    public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

    /// <inheritdoc />
    public int IncomingBufferLength { get; private set; } = 0;

    /// <summary>
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    /// </summary>
    public int ThrottleTimeMs { get; set; } = 0;

    /// <summary>
    /// The top level response error code.
    /// </summary>
    public short ErrorCode { get; set; } = 0;

    /// <inheritdoc />
    public ErrorCodes Code => (ErrorCodes)ErrorCode;

    /// <summary>
    /// The topics to fetch.
    /// </summary>
    public List<TopicSnapshotMessage> Topics { get; set; } = new ();

    /// <summary>
    /// Endpoints for all current-leaders enumerated in PartitionSnapshot.
    /// </summary>
    public NodeEndpointCollection NodeEndpoints { get; set; } = new ();

    /// <summary>
    /// The basic constructor of the message FetchSnapshotResponseMessage
    /// </summary>
    public FetchSnapshotResponseMessage()
    {
    }

    /// <summary>
    /// Base constructor for deserializing message FetchSnapshotResponseMessage
    /// </summary>
    public FetchSnapshotResponseMessage(ref BufferReader reader, ApiVersion version)
        : this()
    {
        IncomingBufferLength = reader.Length;
        Read(ref reader, version);
    }

    /// <inheritdoc />
    public void Read(ref BufferReader reader, ApiVersion version)
    {
        ThrottleTimeMs = reader.ReadInt();
        ErrorCode = reader.ReadShort();
        {
            int arrayLength;
            arrayLength = reader.ReadVarUInt32() - 1;
            if (arrayLength < 0)
            {
                throw new Exception("non-nullable field Topics was serialized as null");
            }
            else
            {
                var newCollection = new List<TopicSnapshotMessage>(arrayLength);
                for (var i = 0; i < arrayLength; i++)
                {
                    newCollection.Add(new TopicSnapshotMessage(ref reader, version));
                }
                Topics = newCollection;
            }
        }
        {
            NodeEndpoints = new ();
        }
        UnknownTaggedFields = null;
        var numTaggedFields = reader.ReadVarInt32();
        for (var t = 0; t < numTaggedFields; t++)
        {
            var tag = reader.ReadVarInt32();
            var size = reader.ReadVarInt32();
            switch (tag)
            {
                case 0:
                {
                    if (version >= ApiVersion.Version1)
                    {
                        int arrayLength;
                        arrayLength = reader.ReadVarUInt32() - 1;
                        if (arrayLength < 0)
                        {
                            throw new Exception("non-nullable field NodeEndpoints was serialized as null");
                        }
                        else
                        {
                            var newCollection = new NodeEndpointCollection(arrayLength);
                            for (var i = 0; i < arrayLength; i++)
                            {
                                newCollection.Add(new NodeEndpointMessage(ref reader, version));
                            }
                            NodeEndpoints = newCollection;
                        }
                        break;
                    }
                    else
                    {
                        throw new Exception($"Tag 0 is not valid for version {version}");
                    }
                }
                default:
                    UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                    break;
            }
        }
    }

    /// <inheritdoc />
    public void Write(ref BufferWriter writer, ApiVersion version)
    {
        var numTaggedFields = 0;
        writer.WriteInt(ThrottleTimeMs);
        writer.WriteShort((short)ErrorCode);
        writer.WriteVarUInt32(Topics.Count + 1);
        foreach (var element in Topics)
        {
            element?.Write(ref writer, version);
        }
        if (version >= ApiVersion.Version1)
        {
            if (NodeEndpoints.Count != 0)
            {
                numTaggedFields++;
            }
        }
        else
        {
            if (NodeEndpoints.Count != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default NodeEndpoints at version {version}");
            }
        }
        var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
        numTaggedFields += rawWriter.FieldsCount;
        writer.WriteVarUInt32(numTaggedFields);
        {
            if (NodeEndpoints.Count != 0)
            {
                writer.WriteVarUInt32(0);
                writer.WriteVarUInt32(NodeEndpoints.Count + 1);
                foreach (var element in NodeEndpoints)
                {
                    element?.Write(ref writer, version);
                }
            }
        }
        rawWriter.WriteRawTags(ref writer, int.MaxValue);
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is FetchSnapshotResponseMessage other && Equals(other);
    }

    /// <inheritdoc />
    public bool Equals(FetchSnapshotResponseMessage? other)
    {
        if (other is null)
        {
            return false;
        }
        if (ThrottleTimeMs != other.ThrottleTimeMs)
        {
            return false;
        }
        if (ErrorCode != other.ErrorCode)
        {
            return false;
        }
        if (Topics is null)
        {
            if (other.Topics is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Topics.SequenceEqual(other.Topics))
            {
                return false;
            }
        }
        if (NodeEndpoints is null)
        {
            if (other.NodeEndpoints is not null)
            {
                return false;
            }
        }
        else
        {
            if (!NodeEndpoints.SequenceEqual(other.NodeEndpoints))
            {
                return false;
            }
        }
        return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hashCode = 0;
        hashCode = HashCode.Combine(hashCode, ThrottleTimeMs, ErrorCode, Topics, NodeEndpoints);
        return hashCode;
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return "FetchSnapshotResponseMessage("
            + "ThrottleTimeMs=" + ThrottleTimeMs
            + ", ErrorCode=" + ErrorCode
            + ", Topics=" + Topics.DeepToString()
            + ", NodeEndpoints=" + NodeEndpoints.DeepToString()
            + ")";
    }

    /// <summary>
    /// Describes the contract for message TopicSnapshotMessage
    /// </summary>
    internal sealed partial class TopicSnapshotMessage: IMessage, IEquatable<TopicSnapshotMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The name of the topic to fetch.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The partitions to fetch.
        /// </summary>
        public List<PartitionSnapshotMessage> Partitions { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message TopicSnapshotMessage
        /// </summary>
        public TopicSnapshotMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message TopicSnapshotMessage
        /// </summary>
        public TopicSnapshotMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of TopicSnapshotMessage");
            }
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    throw new Exception("non-nullable field Name was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Name had invalid length {length}");
                }
                else
                {
                    Name = reader.ReadString(length);
                }
            }
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Partitions was serialized as null");
                }
                else
                {
                    var newCollection = new List<PartitionSnapshotMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new PartitionSnapshotMessage(ref reader, version));
                    }
                    Partitions = newCollection;
                }
            }
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            {
                writer.WriteCompactString(Name);
            }
            writer.WriteVarUInt32(Partitions.Count + 1);
            foreach (var element in Partitions)
            {
                element?.Write(ref writer, version);
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is TopicSnapshotMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(TopicSnapshotMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (Name is null)
            {
                if (other.Name is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Name.Equals(other.Name))
                {
                    return false;
                }
            }
            if (Partitions is null)
            {
                if (other.Partitions is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Partitions.SequenceEqual(other.Partitions))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, Name, Partitions);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "TopicSnapshotMessage("
                + "Name=" + (string.IsNullOrWhiteSpace(Name) ? "null" : Name)
                + ", Partitions=" + Partitions.DeepToString()
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message PartitionSnapshotMessage
    /// </summary>
    internal sealed partial class PartitionSnapshotMessage: IMessage, IEquatable<PartitionSnapshotMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The partition index.
        /// </summary>
        public int Index { get; set; } = 0;

        /// <summary>
        /// The error code, or 0 if there was no fetch error.
        /// </summary>
        public short ErrorCode { get; set; } = 0;

        /// <inheritdoc />
        public ErrorCodes Code => (ErrorCodes)ErrorCode;

        /// <summary>
        /// The snapshot endOffset and epoch fetched.
        /// </summary>
        public SnapshotIdMessage SnapshotId { get; set; } = new ();

        /// <summary>
        /// The leader of the partition at the time of the snapshot.
        /// </summary>
        public LeaderIdAndEpochMessage CurrentLeader { get; set; } = new ();

        /// <summary>
        /// The total size of the snapshot.
        /// </summary>
        public long Size { get; set; } = 0;

        /// <summary>
        /// The starting byte position within the snapshot included in the Bytes field.
        /// </summary>
        public long Position { get; set; } = 0;

        /// <summary>
        /// Snapshot data in records format which may not be aligned on an offset boundary.
        /// </summary>
        public Records? UnalignedRecords { get; set; } = null;

        /// <summary>
        /// The basic constructor of the message PartitionSnapshotMessage
        /// </summary>
        public PartitionSnapshotMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message PartitionSnapshotMessage
        /// </summary>
        public PartitionSnapshotMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of PartitionSnapshotMessage");
            }
            Index = reader.ReadInt();
            ErrorCode = reader.ReadShort();
            {
                SnapshotId = new SnapshotIdMessage(ref reader, version);
            }
            {
                CurrentLeader = new ();
            }
            Size = reader.ReadLong();
            Position = reader.ReadLong();
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    throw new Exception("non-nullable field UnalignedRecords was serialized as null");
                }
                else
                {
                    UnalignedRecords = reader.ReadRecords(length);
                }
            }
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    case 0:
                    {
                        CurrentLeader = new LeaderIdAndEpochMessage(ref reader, version);
                        break;
                    }
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            writer.WriteInt(Index);
            writer.WriteShort((short)ErrorCode);
            SnapshotId?.Write(ref writer, version);
            if (!CurrentLeader.Equals(new ()))
            {
                numTaggedFields++;
            }
            writer.WriteLong(Size);
            writer.WriteLong(Position);
            writer.WriteVarUInt32((UnalignedRecords?.SizeInBytes ?? 0) + 1);
            writer.WriteRecords(UnalignedRecords);
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            {
                if (!CurrentLeader.Equals(new ()))
                {
                    writer.WriteVarUInt32(0);
                    CurrentLeader?.Write(ref writer, version);
                }
            }
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is PartitionSnapshotMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(PartitionSnapshotMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (Index != other.Index)
            {
                return false;
            }
            if (ErrorCode != other.ErrorCode)
            {
                return false;
            }
            if (SnapshotId is null)
            {
                if (other.SnapshotId is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!SnapshotId.Equals(other.SnapshotId))
                {
                    return false;
                }
            }
            if (CurrentLeader is null)
            {
                if (other.CurrentLeader is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!CurrentLeader.Equals(other.CurrentLeader))
                {
                    return false;
                }
            }
            if (Size != other.Size)
            {
                return false;
            }
            if (Position != other.Position)
            {
                return false;
            }
            if (!ReferenceEquals(UnalignedRecords,other.UnalignedRecords))
            {
                return false;
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, Index, ErrorCode, SnapshotId, CurrentLeader, Size, Position, UnalignedRecords);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "PartitionSnapshotMessage("
                + "Index=" + Index
                + ", ErrorCode=" + ErrorCode
                + ", SnapshotId=" + SnapshotId.ToString()
                + ", CurrentLeader=" + CurrentLeader.ToString()
                + ", Size=" + Size
                + ", Position=" + Position
                + ", UnalignedRecords=" + UnalignedRecords
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message SnapshotIdMessage
    /// </summary>
    internal sealed partial class SnapshotIdMessage: IMessage, IEquatable<SnapshotIdMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The snapshot end offset.
        /// </summary>
        public long EndOffset { get; set; } = 0;

        /// <summary>
        /// The snapshot epoch.
        /// </summary>
        public int Epoch { get; set; } = 0;

        /// <summary>
        /// The basic constructor of the message SnapshotIdMessage
        /// </summary>
        public SnapshotIdMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message SnapshotIdMessage
        /// </summary>
        public SnapshotIdMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of SnapshotIdMessage");
            }
            EndOffset = reader.ReadLong();
            Epoch = reader.ReadInt();
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            writer.WriteLong(EndOffset);
            writer.WriteInt(Epoch);
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is SnapshotIdMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(SnapshotIdMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (EndOffset != other.EndOffset)
            {
                return false;
            }
            if (Epoch != other.Epoch)
            {
                return false;
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, EndOffset, Epoch);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "SnapshotIdMessage("
                + "EndOffset=" + EndOffset
                + ", Epoch=" + Epoch
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message LeaderIdAndEpochMessage
    /// </summary>
    internal sealed partial class LeaderIdAndEpochMessage: IMessage, IEquatable<LeaderIdAndEpochMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The ID of the current leader or -1 if the leader is unknown.
        /// </summary>
        public int LeaderId { get; set; } = 0;

        /// <summary>
        /// The latest known leader epoch.
        /// </summary>
        public int LeaderEpoch { get; set; } = 0;

        /// <summary>
        /// The basic constructor of the message LeaderIdAndEpochMessage
        /// </summary>
        public LeaderIdAndEpochMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message LeaderIdAndEpochMessage
        /// </summary>
        public LeaderIdAndEpochMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of LeaderIdAndEpochMessage");
            }
            LeaderId = reader.ReadInt();
            LeaderEpoch = reader.ReadInt();
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            writer.WriteInt(LeaderId);
            writer.WriteInt(LeaderEpoch);
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is LeaderIdAndEpochMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(LeaderIdAndEpochMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (LeaderId != other.LeaderId)
            {
                return false;
            }
            if (LeaderEpoch != other.LeaderEpoch)
            {
                return false;
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, LeaderId, LeaderEpoch);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "LeaderIdAndEpochMessage("
                + "LeaderId=" + LeaderId
                + ", LeaderEpoch=" + LeaderEpoch
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message NodeEndpointMessage
    /// </summary>
    internal sealed partial class NodeEndpointMessage: IMessage, IEquatable<NodeEndpointMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The ID of the associated node.
        /// </summary>
        public int NodeId { get; set; } = 0;

        /// <summary>
        /// The node&#39;s hostname.
        /// </summary>
        public string Host { get; set; } = string.Empty;

        /// <summary>
        /// The node&#39;s port.
        /// </summary>
        public ushort Port { get; set; } = 0;

        /// <summary>
        /// The basic constructor of the message NodeEndpointMessage
        /// </summary>
        public NodeEndpointMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message NodeEndpointMessage
        /// </summary>
        public NodeEndpointMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of NodeEndpointMessage");
            }
            NodeId = reader.ReadInt();
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    throw new Exception("non-nullable field Host was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Host had invalid length {length}");
                }
                else
                {
                    Host = reader.ReadString(length);
                }
            }
            Port = reader.ReadUShort();
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            if (version < ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't write version {version} of NodeEndpointMessage");
            }
            var numTaggedFields = 0;
            writer.WriteInt(NodeId);
            {
                writer.WriteCompactString(Host);
            }
            writer.WriteUShort(Port);
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is NodeEndpointMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(NodeEndpointMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (NodeId != other.NodeId)
            {
                return false;
            }
            if (Host is null)
            {
                if (other.Host is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Host.Equals(other.Host))
                {
                    return false;
                }
            }
            if (Port != other.Port)
            {
                return false;
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, NodeId);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "NodeEndpointMessage("
                + "NodeId=" + NodeId
                + ", Host=" + (string.IsNullOrWhiteSpace(Host) ? "null" : Host)
                + ", Port=" + Port
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message NodeEndpointCollection
    /// </summary>
    internal sealed partial class NodeEndpointCollection: HashSet<NodeEndpointMessage>
    {
        /// <summary>
        /// Basic collection constructor
        /// </summary>
        public NodeEndpointCollection()
        {
        }

        /// <summary>
        /// Basic collection constructor with the ability to set capacity
        /// </summary>
        public NodeEndpointCollection(int capacity)
            : base(capacity)
        {
        }
        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return SetEquals((IEnumerable<NodeEndpointMessage>)obj);
        }
    }
}
