//AA-5C-A4-AB-8D-AC-F9-D3-69-59-EF-91-60-F2-35-E9-E4-43-7A-41-09-EC-01-88-0D-F0-58-6C-54-0B-7D-BC
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Exceptions;
using NKafka.Protocol;
using NKafka.Protocol.Buffers;
using NKafka.Protocol.Extensions;
using NKafka.Protocol.Records;
using System.Text;

namespace NKafka.Messages;

/// <summary>
/// Describes the contract for message LeaveGroupResponseMessage
/// </summary>
internal sealed partial class LeaveGroupResponseMessage: IResponseMessage, IEquatable<LeaveGroupResponseMessage>
{
    /// <inheritdoc />
    public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

    /// <inheritdoc />
    public int IncomingBufferLength { get; private set; } = 0;

    /// <summary>
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    /// </summary>
    public int ThrottleTimeMs { get; set; } = 0;

    /// <summary>
    /// The error code, or 0 if there was no error.
    /// </summary>
    public short ErrorCode { get; set; } = 0;

    /// <inheritdoc />
    public ErrorCodes Code => (ErrorCodes)ErrorCode;

    /// <summary>
    /// List of leaving member responses.
    /// </summary>
    public List<MemberResponseMessage> Members { get; set; } = new ();

    /// <summary>
    /// The basic constructor of the message LeaveGroupResponseMessage
    /// </summary>
    public LeaveGroupResponseMessage()
    {
    }

    /// <summary>
    /// Base constructor for deserializing message LeaveGroupResponseMessage
    /// </summary>
    public LeaveGroupResponseMessage(ref BufferReader reader, ApiVersion version)
        : this()
    {
        IncomingBufferLength = reader.Length;
        Read(ref reader, version);
    }

    /// <inheritdoc />
    public void Read(ref BufferReader reader, ApiVersion version)
    {
        if (version >= ApiVersion.Version1)
        {
            ThrottleTimeMs = reader.ReadInt();
        }
        else
        {
            ThrottleTimeMs = 0;
        }
        ErrorCode = reader.ReadShort();
        if (version >= ApiVersion.Version3)
        {
            if (version >= ApiVersion.Version4)
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Members was serialized as null");
                }
                else
                {
                    var newCollection = new List<MemberResponseMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new MemberResponseMessage(ref reader, version));
                    }
                    Members = newCollection;
                }
            }
            else
            {
                int arrayLength;
                arrayLength = reader.ReadInt();
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Members was serialized as null");
                }
                else
                {
                    var newCollection = new List<MemberResponseMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new MemberResponseMessage(ref reader, version));
                    }
                    Members = newCollection;
                }
            }
        }
        else
        {
            Members = new ();
        }
        UnknownTaggedFields = null;
        if (version >= ApiVersion.Version4)
        {
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }
    }

    /// <inheritdoc />
    public void Write(ref BufferWriter writer, ApiVersion version)
    {
        var numTaggedFields = 0;
        if (version >= ApiVersion.Version1)
        {
            writer.WriteInt(ThrottleTimeMs);
        }
        writer.WriteShort((short)ErrorCode);
        if (version >= ApiVersion.Version3)
        {
            if (version >= ApiVersion.Version4)
            {
                writer.WriteVarUInt32(Members.Count + 1);
                foreach (var element in Members)
                {
                    element?.Write(ref writer, version);
                }
            }
            else
            {
                writer.WriteInt(Members.Count);
                foreach (var element in Members)
                {
                    element?.Write(ref writer, version);
                }
            }
        }
        else
        {
            if (Members.Count != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default Members at version {version}");
            }
        }
        var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
        numTaggedFields += rawWriter.FieldsCount;
        if (version >= ApiVersion.Version4)
        {
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }
        else
        {
            if (numTaggedFields > 0)
            {
                throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
            }
        }
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is LeaveGroupResponseMessage other && Equals(other);
    }

    /// <inheritdoc />
    public bool Equals(LeaveGroupResponseMessage? other)
    {
        if (other is null)
        {
            return false;
        }
        if (ThrottleTimeMs != other.ThrottleTimeMs)
        {
            return false;
        }
        if (ErrorCode != other.ErrorCode)
        {
            return false;
        }
        if (Members is null)
        {
            if (other.Members is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Members.SequenceEqual(other.Members))
            {
                return false;
            }
        }
        return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hashCode = 0;
        hashCode = HashCode.Combine(hashCode, ThrottleTimeMs, ErrorCode, Members);
        return hashCode;
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return "LeaveGroupResponseMessage("
            + "ThrottleTimeMs=" + ThrottleTimeMs
            + ", ErrorCode=" + ErrorCode
            + ", Members=" + Members.DeepToString()
            + ")";
    }

    /// <summary>
    /// Describes the contract for message MemberResponseMessage
    /// </summary>
    internal sealed partial class MemberResponseMessage: IMessage, IEquatable<MemberResponseMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The member ID to remove from the group.
        /// </summary>
        public string MemberId { get; set; } = string.Empty;

        /// <summary>
        /// The group instance ID to remove from the group.
        /// </summary>
        public string GroupInstanceId { get; set; } = string.Empty;

        /// <summary>
        /// The error code, or 0 if there was no error.
        /// </summary>
        public short ErrorCode { get; set; } = 0;

        /// <inheritdoc />
        public ErrorCodes Code => (ErrorCodes)ErrorCode;

        /// <summary>
        /// The basic constructor of the message MemberResponseMessage
        /// </summary>
        public MemberResponseMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message MemberResponseMessage
        /// </summary>
        public MemberResponseMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version5)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of MemberResponseMessage");
            }
            {
                int length;
                if (version >= ApiVersion.Version4)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    throw new Exception("non-nullable field MemberId was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field MemberId had invalid length {length}");
                }
                else
                {
                    MemberId = reader.ReadString(length);
                }
            }
            {
                int length;
                if (version >= ApiVersion.Version4)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    GroupInstanceId = null;
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field GroupInstanceId had invalid length {length}");
                }
                else
                {
                    GroupInstanceId = reader.ReadString(length);
                }
            }
            ErrorCode = reader.ReadShort();
            UnknownTaggedFields = null;
            if (version >= ApiVersion.Version4)
            {
                var numTaggedFields = reader.ReadVarInt32();
                for (var t = 0; t < numTaggedFields; t++)
                {
                    var tag = reader.ReadVarInt32();
                    var size = reader.ReadVarInt32();
                    switch (tag)
                    {
                        default:
                            UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                            break;
                    }
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            if (version < ApiVersion.Version3)
            {
                throw new UnsupportedVersionException($"Can't write version {version} of MemberResponseMessage");
            }
            var numTaggedFields = 0;
            {
                if (version >= ApiVersion.Version4)
                {
                    writer.WriteCompactString(MemberId);
                }
                else
                {
                    writer.WriteInt16String(MemberId);
                }
            }
            if (GroupInstanceId is null)
            {
                if (version >= ApiVersion.Version4)
                {
                    writer.WriteNullableCompactString(GroupInstanceId);
                }
                else
                {
                    writer.WriteNullableInt16String(GroupInstanceId);
                }
            }
            else
            {
                if (version >= ApiVersion.Version4)
                {
                    writer.WriteCompactString(GroupInstanceId);
                }
                else
                {
                    writer.WriteInt16String(GroupInstanceId);
                }
            }
            writer.WriteShort((short)ErrorCode);
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            if (version >= ApiVersion.Version4)
            {
                writer.WriteVarUInt32(numTaggedFields);
                rawWriter.WriteRawTags(ref writer, int.MaxValue);
            }
            else
            {
                if (numTaggedFields > 0)
                {
                    throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
                }
            }
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is MemberResponseMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(MemberResponseMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (MemberId is null)
            {
                if (other.MemberId is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!MemberId.Equals(other.MemberId))
                {
                    return false;
                }
            }
            if (GroupInstanceId is null)
            {
                if (other.GroupInstanceId is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!GroupInstanceId.Equals(other.GroupInstanceId))
                {
                    return false;
                }
            }
            if (ErrorCode != other.ErrorCode)
            {
                return false;
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, MemberId, GroupInstanceId, ErrorCode);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "MemberResponseMessage("
                + "MemberId=" + (string.IsNullOrWhiteSpace(MemberId) ? "null" : MemberId)
                + ", GroupInstanceId=" + (string.IsNullOrWhiteSpace(GroupInstanceId) ? "null" : GroupInstanceId)
                + ", ErrorCode=" + ErrorCode
                + ")";
        }
    }
}
