//B4-DE-85-C2-50-28-A8-73-D7-D2-89-14-9F-09-19-CE-E9-E9-1A-C0-0E-68-EF-B8-7E-39-15-1B-62-48-27-88
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Exceptions;
using NKafka.Protocol;
using NKafka.Protocol.Buffers;
using NKafka.Protocol.Extensions;
using NKafka.Protocol.Records;
using System.Text;

namespace NKafka.Messages;

/// <summary>
/// Describes the contract for message MetadataRequestMessage
/// </summary>
internal sealed partial class MetadataRequestMessage: IRequestMessage, IEquatable<MetadataRequestMessage>
{
    /// <inheritdoc />
    public ApiKeys ApiKey => ApiKeys.Metadata;

    /// <summary>
    /// Indicates whether the request is accessed by any broker or only by the controller
    /// </summary>
    public const bool ONLY_CONTROLLER = false;

    /// <inheritdoc />
    public bool OnlyController => ONLY_CONTROLLER;

    /// <inheritdoc />
    public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

    /// <inheritdoc />
    public int IncomingBufferLength { get; private set; } = 0;

    /// <summary>
    /// The topics to fetch metadata for.
    /// </summary>
    public List<MetadataRequestTopicMessage> Topics { get; set; } = new ();

    /// <summary>
    /// If this is true, the broker may auto-create topics that we requested which do not already exist, if it is configured to do so.
    /// </summary>
    public bool AllowAutoTopicCreation { get; set; } = true;

    /// <summary>
    /// Whether to include cluster authorized operations.
    /// </summary>
    public bool IncludeClusterAuthorizedOperations { get; set; } = false;

    /// <summary>
    /// Whether to include topic authorized operations.
    /// </summary>
    public bool IncludeTopicAuthorizedOperations { get; set; } = false;

    /// <summary>
    /// The basic constructor of the message MetadataRequestMessage
    /// </summary>
    public MetadataRequestMessage()
    {
    }

    /// <summary>
    /// Base constructor for deserializing message MetadataRequestMessage
    /// </summary>
    public MetadataRequestMessage(ref BufferReader reader, ApiVersion version)
        : this()
    {
        IncomingBufferLength = reader.Length;
        Read(ref reader, version);
    }

    /// <inheritdoc />
    public void Read(ref BufferReader reader, ApiVersion version)
    {
        {
            if (version >= ApiVersion.Version9)
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    Topics = null;
                }
                else
                {
                    var newCollection = new List<MetadataRequestTopicMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new MetadataRequestTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
            else
            {
                int arrayLength;
                arrayLength = reader.ReadInt();
                if (arrayLength < 0)
                {
                    Topics = null;
                }
                else
                {
                    var newCollection = new List<MetadataRequestTopicMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new MetadataRequestTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
        }
        AllowAutoTopicCreation = reader.ReadByte() != 0;
        if (version >= ApiVersion.Version8 && version <= ApiVersion.Version10)
        {
            IncludeClusterAuthorizedOperations = reader.ReadByte() != 0;
        }
        else
        {
            IncludeClusterAuthorizedOperations = false;
        }
        if (version >= ApiVersion.Version8)
        {
            IncludeTopicAuthorizedOperations = reader.ReadByte() != 0;
        }
        else
        {
            IncludeTopicAuthorizedOperations = false;
        }
        UnknownTaggedFields = null;
        if (version >= ApiVersion.Version9)
        {
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }
    }

    /// <inheritdoc />
    public void Write(ref BufferWriter writer, ApiVersion version)
    {
        var numTaggedFields = 0;
        if (version >= ApiVersion.Version9)
        {
            if (Topics is null)
            {
                writer.WriteVarUInt32(0);
            }
            else
            {
                writer.WriteVarUInt32(Topics.Count + 1);
                foreach (var element in Topics)
                {
                    element?.Write(ref writer, version);
                }
            }
        }
        else
        {
            if (Topics is null)
            {
                writer.WriteInt(-1);
            }
            else
            {
                writer.WriteInt(Topics.Count);
                foreach (var element in Topics)
                {
                    element?.Write(ref writer, version);
                }
            }
        }
        writer.WriteBool(AllowAutoTopicCreation);
        if (version >= ApiVersion.Version8 && version <= ApiVersion.Version10)
        {
            writer.WriteBool(IncludeClusterAuthorizedOperations);
        }
        else
        {
            if (IncludeClusterAuthorizedOperations)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default IncludeClusterAuthorizedOperations at version {version}");
            }
        }
        if (version >= ApiVersion.Version8)
        {
            writer.WriteBool(IncludeTopicAuthorizedOperations);
        }
        else
        {
            if (IncludeTopicAuthorizedOperations)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default IncludeTopicAuthorizedOperations at version {version}");
            }
        }
        var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
        numTaggedFields += rawWriter.FieldsCount;
        if (version >= ApiVersion.Version9)
        {
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }
        else
        {
            if (numTaggedFields > 0)
            {
                throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
            }
        }
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is MetadataRequestMessage other && Equals(other);
    }

    /// <inheritdoc />
    public bool Equals(MetadataRequestMessage? other)
    {
        if (other is null)
        {
            return false;
        }
        if (Topics is null)
        {
            if (other.Topics is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Topics.SequenceEqual(other.Topics))
            {
                return false;
            }
        }
        if (AllowAutoTopicCreation != other.AllowAutoTopicCreation)
        {
            return false;
        }
        if (IncludeClusterAuthorizedOperations != other.IncludeClusterAuthorizedOperations)
        {
            return false;
        }
        if (IncludeTopicAuthorizedOperations != other.IncludeTopicAuthorizedOperations)
        {
            return false;
        }
        return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hashCode = 0;
        hashCode = HashCode.Combine(hashCode, Topics, AllowAutoTopicCreation, IncludeClusterAuthorizedOperations, IncludeTopicAuthorizedOperations);
        return hashCode;
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return "MetadataRequestMessage("
            + "Topics=" + (Topics is null ? "null" : Topics.DeepToString())
            + ", AllowAutoTopicCreation=" + (AllowAutoTopicCreation ? "true" : "false")
            + ", IncludeClusterAuthorizedOperations=" + (IncludeClusterAuthorizedOperations ? "true" : "false")
            + ", IncludeTopicAuthorizedOperations=" + (IncludeTopicAuthorizedOperations ? "true" : "false")
            + ")";
    }

    /// <summary>
    /// Describes the contract for message MetadataRequestTopicMessage
    /// </summary>
    internal sealed partial class MetadataRequestTopicMessage: IMessage, IEquatable<MetadataRequestTopicMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The topic id.
        /// </summary>
        public Guid TopicId { get; set; } = Guid.Empty;

        /// <summary>
        /// The topic name.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The basic constructor of the message MetadataRequestTopicMessage
        /// </summary>
        public MetadataRequestTopicMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message MetadataRequestTopicMessage
        /// </summary>
        public MetadataRequestTopicMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version < ApiVersion.Version4 || version > ApiVersion.Version13)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of MetadataRequestTopicMessage");
            }
            if (version >= ApiVersion.Version10)
            {
                TopicId = reader.ReadGuid();
            }
            else
            {
                TopicId = Guid.Empty;
            }
            {
                int length;
                if (version >= ApiVersion.Version9)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    if (version >= ApiVersion.Version10)
                    {
                        Name = null;
                    }
                    else
                    {
                        throw new Exception("non-nullable field Name was serialized as null");
                    }
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Name had invalid length {length}");
                }
                else
                {
                    Name = reader.ReadString(length);
                }
            }
            UnknownTaggedFields = null;
            if (version >= ApiVersion.Version9)
            {
                var numTaggedFields = reader.ReadVarInt32();
                for (var t = 0; t < numTaggedFields; t++)
                {
                    var tag = reader.ReadVarInt32();
                    var size = reader.ReadVarInt32();
                    switch (tag)
                    {
                        default:
                            UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                            break;
                    }
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            if (version >= ApiVersion.Version10)
            {
                writer.WriteGuid(TopicId);
            }
            if (Name is null)
            {
                if (version >= ApiVersion.Version10)
                {
                    writer.WriteVarUInt32(0);
                }
                else
                {
                    throw new NullReferenceException();                }
            }
            else
            {
                var stringBytes = Encoding.UTF8.GetBytes(Name);
                if (version >= ApiVersion.Version9)
                {
                    writer.WriteVarUInt32(stringBytes.Length + 1);
                }
                else
                {
                    writer.WriteShort((short)stringBytes.Length);
                }
                writer.WriteBytes(stringBytes);
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            if (version >= ApiVersion.Version9)
            {
                writer.WriteVarUInt32(numTaggedFields);
                rawWriter.WriteRawTags(ref writer, int.MaxValue);
            }
            else
            {
                if (numTaggedFields > 0)
                {
                    throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
                }
            }
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is MetadataRequestTopicMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(MetadataRequestTopicMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (!TopicId.Equals(other.TopicId))
            {
                return false;
            }
            if (Name is null)
            {
                if (other.Name is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Name.Equals(other.Name))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, TopicId, Name);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "MetadataRequestTopicMessage("
                + "TopicId=" + TopicId
                + ", Name=" + (string.IsNullOrWhiteSpace(Name) ? "null" : Name)
                + ")";
        }
    }
}
