//02-05-AF-88-55-26-7F-E9-9C-D7-55-91-EF-C3-03-A5-9C-7E-45-E1-23-56-24-E0-82-A7-00-C8-07-07-3F-EF
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Exceptions;
using NKafka.Protocol;
using NKafka.Protocol.Buffers;
using NKafka.Protocol.Extensions;
using NKafka.Protocol.Records;
using System.Text;

namespace NKafka.Messages;

/// <summary>
/// Describes the contract for message OffsetFetchRequestMessage
/// </summary>
internal sealed partial class OffsetFetchRequestMessage: IRequestMessage, IEquatable<OffsetFetchRequestMessage>
{
    /// <inheritdoc />
    public ApiKeys ApiKey => ApiKeys.OffsetFetch;

    /// <summary>
    /// Indicates whether the request is accessed by any broker or only by the controller
    /// </summary>
    public const bool ONLY_CONTROLLER = false;

    /// <inheritdoc />
    public bool OnlyController => ONLY_CONTROLLER;

    /// <inheritdoc />
    public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

    /// <inheritdoc />
    public int IncomingBufferLength { get; private set; } = 0;

    /// <summary>
    /// The group to fetch offsets for.
    /// </summary>
    public string GroupId { get; set; } = string.Empty;

    /// <summary>
    /// Each topic we would like to fetch offsets for, or null to fetch offsets for all topics.
    /// </summary>
    public List<OffsetFetchRequestTopicMessage> Topics { get; set; } = new ();

    /// <summary>
    /// Each group we would like to fetch offsets for.
    /// </summary>
    public List<OffsetFetchRequestGroupMessage> Groups { get; set; } = new ();

    /// <summary>
    /// Whether broker should hold on returning unstable offsets but set a retriable error code for the partitions.
    /// </summary>
    public bool RequireStable { get; set; } = false;

    /// <summary>
    /// The basic constructor of the message OffsetFetchRequestMessage
    /// </summary>
    public OffsetFetchRequestMessage()
    {
    }

    /// <summary>
    /// Base constructor for deserializing message OffsetFetchRequestMessage
    /// </summary>
    public OffsetFetchRequestMessage(ref BufferReader reader, ApiVersion version)
        : this()
    {
        IncomingBufferLength = reader.Length;
        Read(ref reader, version);
    }

    /// <inheritdoc />
    public void Read(ref BufferReader reader, ApiVersion version)
    {
        if (version <= ApiVersion.Version7)
        {
            int length;
            if (version >= ApiVersion.Version6)
            {
                length = reader.ReadVarUInt32() - 1;
            }
            else
            {
                length = reader.ReadShort();
            }
            if (length < 0)
            {
                throw new Exception("non-nullable field GroupId was serialized as null");
            }
            else if (length > 0x7fff)
            {
                throw new Exception($"string field GroupId had invalid length {length}");
            }
            else
            {
                GroupId = reader.ReadString(length);
            }
        }
        else
        {
            GroupId = string.Empty;
        }
        if (version <= ApiVersion.Version7)
        {
            if (version >= ApiVersion.Version6)
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    Topics = null;
                }
                else
                {
                    var newCollection = new List<OffsetFetchRequestTopicMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new OffsetFetchRequestTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
            else
            {
                int arrayLength;
                arrayLength = reader.ReadInt();
                if (arrayLength < 0)
                {
                    if (version >= ApiVersion.Version2)
                    {
                        Topics = null;
                    }
                    else
                    {
                        throw new Exception("non-nullable field Topics was serialized as null");
                    }
                }
                else
                {
                    var newCollection = new List<OffsetFetchRequestTopicMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new OffsetFetchRequestTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
        }
        else
        {
            Topics = new ();
        }
        if (version >= ApiVersion.Version8)
        {
            int arrayLength;
            arrayLength = reader.ReadVarUInt32() - 1;
            if (arrayLength < 0)
            {
                throw new Exception("non-nullable field Groups was serialized as null");
            }
            else
            {
                var newCollection = new List<OffsetFetchRequestGroupMessage>(arrayLength);
                for (var i = 0; i < arrayLength; i++)
                {
                    newCollection.Add(new OffsetFetchRequestGroupMessage(ref reader, version));
                }
                Groups = newCollection;
            }
        }
        else
        {
            Groups = new ();
        }
        if (version >= ApiVersion.Version7)
        {
            RequireStable = reader.ReadByte() != 0;
        }
        else
        {
            RequireStable = false;
        }
        UnknownTaggedFields = null;
        if (version >= ApiVersion.Version6)
        {
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }
    }

    /// <inheritdoc />
    public void Write(ref BufferWriter writer, ApiVersion version)
    {
        var numTaggedFields = 0;
        if (version <= ApiVersion.Version7)
        {
            {
                if (version >= ApiVersion.Version6)
                {
                    writer.WriteCompactString(GroupId);
                }
                else
                {
                    writer.WriteInt16String(GroupId);
                }
            }
        }
        else
        {
            if (!GroupId.Equals(string.Empty))
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default GroupId at version {version}");
            }
        }
        if (version <= ApiVersion.Version7)
        {
            if (version >= ApiVersion.Version6)
            {
                if (Topics is null)
                {
                    writer.WriteVarUInt32(0);
                }
                else
                {
                    writer.WriteVarUInt32(Topics.Count + 1);
                    foreach (var element in Topics)
                    {
                        element?.Write(ref writer, version);
                    }
                }
            }
            else
            {
                if (Topics is null)
                {
                    if (version >= ApiVersion.Version2)
                    {
                        writer.WriteInt(-1);
                    }
                    else
                    {
                        throw new NullReferenceException();                    }
                }
                else
                {
                    writer.WriteInt(Topics.Count);
                    foreach (var element in Topics)
                    {
                        element?.Write(ref writer, version);
                    }
                }
            }
        }
        else
        {
            if (Topics is null || Topics.Count != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default Topics at version {version}");
            }
        }
        if (version >= ApiVersion.Version8)
        {
            writer.WriteVarUInt32(Groups.Count + 1);
            foreach (var element in Groups)
            {
                element?.Write(ref writer, version);
            }
        }
        else
        {
            if (Groups.Count != 0)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default Groups at version {version}");
            }
        }
        if (version >= ApiVersion.Version7)
        {
            writer.WriteBool(RequireStable);
        }
        else
        {
            if (RequireStable)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default RequireStable at version {version}");
            }
        }
        var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
        numTaggedFields += rawWriter.FieldsCount;
        if (version >= ApiVersion.Version6)
        {
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }
        else
        {
            if (numTaggedFields > 0)
            {
                throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
            }
        }
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is OffsetFetchRequestMessage other && Equals(other);
    }

    /// <inheritdoc />
    public bool Equals(OffsetFetchRequestMessage? other)
    {
        if (other is null)
        {
            return false;
        }
        if (GroupId is null)
        {
            if (other.GroupId is not null)
            {
                return false;
            }
        }
        else
        {
            if (!GroupId.Equals(other.GroupId))
            {
                return false;
            }
        }
        if (Topics is null)
        {
            if (other.Topics is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Topics.SequenceEqual(other.Topics))
            {
                return false;
            }
        }
        if (Groups is null)
        {
            if (other.Groups is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Groups.SequenceEqual(other.Groups))
            {
                return false;
            }
        }
        if (RequireStable != other.RequireStable)
        {
            return false;
        }
        return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hashCode = 0;
        hashCode = HashCode.Combine(hashCode, GroupId, Topics, Groups, RequireStable);
        return hashCode;
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return "OffsetFetchRequestMessage("
            + "GroupId=" + (string.IsNullOrWhiteSpace(GroupId) ? "null" : GroupId)
            + ", Topics=" + (Topics is null ? "null" : Topics.DeepToString())
            + ", Groups=" + Groups.DeepToString()
            + ", RequireStable=" + (RequireStable ? "true" : "false")
            + ")";
    }

    /// <summary>
    /// Describes the contract for message OffsetFetchRequestTopicMessage
    /// </summary>
    internal sealed partial class OffsetFetchRequestTopicMessage: IMessage, IEquatable<OffsetFetchRequestTopicMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The topic name.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The partition indexes we would like to fetch offsets for.
        /// </summary>
        public List<int> PartitionIndexes { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message OffsetFetchRequestTopicMessage
        /// </summary>
        public OffsetFetchRequestTopicMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message OffsetFetchRequestTopicMessage
        /// </summary>
        public OffsetFetchRequestTopicMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version < ApiVersion.Version1)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of OffsetFetchRequestTopicMessage");
            }
            {
                int length;
                if (version >= ApiVersion.Version6)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    throw new Exception("non-nullable field Name was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Name had invalid length {length}");
                }
                else
                {
                    Name = reader.ReadString(length);
                }
            }
            {
                int arrayLength;
                if (version >= ApiVersion.Version6)
                {
                    arrayLength = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    arrayLength = reader.ReadInt();
                }
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field PartitionIndexes was serialized as null");
                }
                else
                {
                    var newCollection = new List<int>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(reader.ReadInt());
                    }
                    PartitionIndexes = newCollection;
                }
            }
            UnknownTaggedFields = null;
            if (version >= ApiVersion.Version6)
            {
                var numTaggedFields = reader.ReadVarInt32();
                for (var t = 0; t < numTaggedFields; t++)
                {
                    var tag = reader.ReadVarInt32();
                    var size = reader.ReadVarInt32();
                    switch (tag)
                    {
                        default:
                            UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                            break;
                    }
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            if (version > ApiVersion.Version7)
            {
                throw new UnsupportedVersionException($"Can't write version {version} of OffsetFetchRequestTopicMessage");
            }
            var numTaggedFields = 0;
            {
                if (version >= ApiVersion.Version6)
                {
                    writer.WriteCompactString(Name);
                }
                else
                {
                    writer.WriteInt16String(Name);
                }
            }
            if (version >= ApiVersion.Version6)
            {
                writer.WriteVarUInt32(PartitionIndexes.Count + 1);
            }
            else
            {
                writer.WriteInt(PartitionIndexes.Count);
            }
            foreach (var element in PartitionIndexes)
            {
                writer.WriteInt(element);
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            if (version >= ApiVersion.Version6)
            {
                writer.WriteVarUInt32(numTaggedFields);
                rawWriter.WriteRawTags(ref writer, int.MaxValue);
            }
            else
            {
                if (numTaggedFields > 0)
                {
                    throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
                }
            }
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is OffsetFetchRequestTopicMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(OffsetFetchRequestTopicMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (Name is null)
            {
                if (other.Name is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Name.Equals(other.Name))
                {
                    return false;
                }
            }
            if (PartitionIndexes is null)
            {
                if (other.PartitionIndexes is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!PartitionIndexes.SequenceEqual(other.PartitionIndexes))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, Name, PartitionIndexes);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "OffsetFetchRequestTopicMessage("
                + "Name=" + (string.IsNullOrWhiteSpace(Name) ? "null" : Name)
                + ", PartitionIndexes=" + PartitionIndexes.DeepToString()
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message OffsetFetchRequestGroupMessage
    /// </summary>
    internal sealed partial class OffsetFetchRequestGroupMessage: IMessage, IEquatable<OffsetFetchRequestGroupMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The group ID.
        /// </summary>
        public string GroupId { get; set; } = string.Empty;

        /// <summary>
        /// The member id.
        /// </summary>
        public string? MemberId { get; set; } = null;

        /// <summary>
        /// The member epoch if using the new consumer protocol (KIP-848).
        /// </summary>
        public int MemberEpoch { get; set; } = -1;

        /// <summary>
        /// Each topic we would like to fetch offsets for, or null to fetch offsets for all topics.
        /// </summary>
        public List<OffsetFetchRequestTopicsMessage> Topics { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message OffsetFetchRequestGroupMessage
        /// </summary>
        public OffsetFetchRequestGroupMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message OffsetFetchRequestGroupMessage
        /// </summary>
        public OffsetFetchRequestGroupMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version10)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of OffsetFetchRequestGroupMessage");
            }
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    throw new Exception("non-nullable field GroupId was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field GroupId had invalid length {length}");
                }
                else
                {
                    GroupId = reader.ReadString(length);
                }
            }
            if (version >= ApiVersion.Version9)
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    MemberId = null;
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field MemberId had invalid length {length}");
                }
                else
                {
                    MemberId = reader.ReadString(length);
                }
            }
            else
            {
                MemberId = null;
            }
            if (version >= ApiVersion.Version9)
            {
                MemberEpoch = reader.ReadInt();
            }
            else
            {
                MemberEpoch = -1;
            }
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    Topics = null;
                }
                else
                {
                    var newCollection = new List<OffsetFetchRequestTopicsMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new OffsetFetchRequestTopicsMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            if (version < ApiVersion.Version8)
            {
                throw new UnsupportedVersionException($"Can't write version {version} of OffsetFetchRequestGroupMessage");
            }
            var numTaggedFields = 0;
            {
                writer.WriteCompactString(GroupId);
            }
            if (version >= ApiVersion.Version9)
            {
                if (MemberId is null)
                {
                    writer.WriteVarUInt32(0);
                }
                else
                {
                    writer.WriteCompactString(MemberId);
                }
            }
            if (version >= ApiVersion.Version9)
            {
                writer.WriteInt(MemberEpoch);
            }
            if (Topics is null)
            {
                writer.WriteVarUInt32(0);
            }
            else
            {
                writer.WriteVarUInt32(Topics.Count + 1);
                foreach (var element in Topics)
                {
                    element?.Write(ref writer, version);
                }
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is OffsetFetchRequestGroupMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(OffsetFetchRequestGroupMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (GroupId is null)
            {
                if (other.GroupId is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!GroupId.Equals(other.GroupId))
                {
                    return false;
                }
            }
            if (MemberId is null)
            {
                if (other.MemberId is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!MemberId.Equals(other.MemberId))
                {
                    return false;
                }
            }
            if (MemberEpoch != other.MemberEpoch)
            {
                return false;
            }
            if (Topics is null)
            {
                if (other.Topics is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Topics.SequenceEqual(other.Topics))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, GroupId, MemberId, MemberEpoch, Topics);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "OffsetFetchRequestGroupMessage("
                + "GroupId=" + (string.IsNullOrWhiteSpace(GroupId) ? "null" : GroupId)
                + ", MemberId=" + (string.IsNullOrWhiteSpace(MemberId) ? "null" : MemberId)
                + ", MemberEpoch=" + MemberEpoch
                + ", Topics=" + (Topics is null ? "null" : Topics.DeepToString())
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message OffsetFetchRequestTopicsMessage
    /// </summary>
    internal sealed partial class OffsetFetchRequestTopicsMessage: IMessage, IEquatable<OffsetFetchRequestTopicsMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The topic name.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The topic ID.
        /// </summary>
        public Guid TopicId { get; set; } = Guid.Empty;

        /// <summary>
        /// The partition indexes we would like to fetch offsets for.
        /// </summary>
        public List<int> PartitionIndexes { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message OffsetFetchRequestTopicsMessage
        /// </summary>
        public OffsetFetchRequestTopicsMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message OffsetFetchRequestTopicsMessage
        /// </summary>
        public OffsetFetchRequestTopicsMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version > ApiVersion.Version10)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of OffsetFetchRequestTopicsMessage");
            }
            if (version <= ApiVersion.Version9)
            {
                int length;
                length = reader.ReadVarUInt32() - 1;
                if (length < 0)
                {
                    throw new Exception("non-nullable field Name was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Name had invalid length {length}");
                }
                else
                {
                    Name = reader.ReadString(length);
                }
            }
            else
            {
                Name = string.Empty;
            }
            if (version >= ApiVersion.Version10)
            {
                TopicId = reader.ReadGuid();
            }
            else
            {
                TopicId = Guid.Empty;
            }
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field PartitionIndexes was serialized as null");
                }
                else
                {
                    var newCollection = new List<int>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(reader.ReadInt());
                    }
                    PartitionIndexes = newCollection;
                }
            }
            UnknownTaggedFields = null;
            var numTaggedFields = reader.ReadVarInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarInt32();
                var size = reader.ReadVarInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            if (version <= ApiVersion.Version9)
            {
                {
                    writer.WriteCompactString(Name);
                }
            }
            if (version >= ApiVersion.Version10)
            {
                writer.WriteGuid(TopicId);
            }
            writer.WriteVarUInt32(PartitionIndexes.Count + 1);
            foreach (var element in PartitionIndexes)
            {
                writer.WriteInt(element);
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is OffsetFetchRequestTopicsMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(OffsetFetchRequestTopicsMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (Name is null)
            {
                if (other.Name is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Name.Equals(other.Name))
                {
                    return false;
                }
            }
            if (!TopicId.Equals(other.TopicId))
            {
                return false;
            }
            if (PartitionIndexes is null)
            {
                if (other.PartitionIndexes is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!PartitionIndexes.SequenceEqual(other.PartitionIndexes))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, Name, TopicId, PartitionIndexes);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "OffsetFetchRequestTopicsMessage("
                + "Name=" + (string.IsNullOrWhiteSpace(Name) ? "null" : Name)
                + ", TopicId=" + TopicId
                + ", PartitionIndexes=" + PartitionIndexes.DeepToString()
                + ")";
        }
    }
}
