//18-90-E9-3E-9A-1C-A7-8D-00-57-AC-12-86-31-05-92-73-0D-A4-B1-21-E3-69-A4-04-F5-70-27-94-1B-90-2D
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Exceptions;
using NKafka.Protocol;
using NKafka.Protocol.Buffers;
using NKafka.Protocol.Extensions;
using NKafka.Protocol.Records;
using System.Text;

namespace NKafka.Messages;

/// <summary>
/// Describes the contract for message OffsetCommitRequestMessage
/// </summary>
internal sealed partial class OffsetCommitRequestMessage: IRequestMessage, IEquatable<OffsetCommitRequestMessage>
{
    /// <inheritdoc />
    public ApiKeys ApiKey => ApiKeys.OffsetCommit;

    /// <summary>
    /// Indicates whether the request is accessed by any broker or only by the controller
    /// </summary>
    public const bool ONLY_CONTROLLER = false;

    /// <inheritdoc />
    public bool OnlyController => ONLY_CONTROLLER;

    /// <inheritdoc />
    public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

    /// <inheritdoc />
    public int IncomingBufferLength { get; private set; } = 0;

    /// <summary>
    /// The unique group identifier.
    /// </summary>
    public string GroupId { get; set; } = string.Empty;

    /// <summary>
    /// The generation of the group if using the classic group protocol or the member epoch if using the consumer protocol.
    /// </summary>
    public int GenerationIdOrMemberEpoch { get; set; } = -1;

    /// <summary>
    /// The member ID assigned by the group coordinator.
    /// </summary>
    public string MemberId { get; set; } = string.Empty;

    /// <summary>
    /// The unique identifier of the consumer instance provided by end user.
    /// </summary>
    public string? GroupInstanceId { get; set; } = null;

    /// <summary>
    /// The time period in ms to retain the offset.
    /// </summary>
    public long RetentionTimeMs { get; set; } = -1;

    /// <summary>
    /// The topics to commit offsets for.
    /// </summary>
    public List<OffsetCommitRequestTopicMessage> Topics { get; set; } = new ();

    /// <summary>
    /// The basic constructor of the message OffsetCommitRequestMessage
    /// </summary>
    public OffsetCommitRequestMessage()
    {
    }

    /// <summary>
    /// Base constructor for deserializing message OffsetCommitRequestMessage
    /// </summary>
    public OffsetCommitRequestMessage(ref BufferReader reader, ApiVersion version)
        : this()
    {
        IncomingBufferLength = reader.Length;
        Read(ref reader, version);
    }

    /// <inheritdoc />
    public void Read(ref BufferReader reader, ApiVersion version)
    {
        {
            int length;
            if (version >= ApiVersion.Version8)
            {
                length = reader.ReadVarUInt32() - 1;
            }
            else
            {
                length = reader.ReadShort();
            }
            if (length < 0)
            {
                throw new Exception("non-nullable field GroupId was serialized as null");
            }
            else if (length > 0x7fff)
            {
                throw new Exception($"string field GroupId had invalid length {length}");
            }
            else
            {
                GroupId = reader.ReadString(length);
            }
        }
        GenerationIdOrMemberEpoch = reader.ReadInt();
        {
            int length;
            if (version >= ApiVersion.Version8)
            {
                length = reader.ReadVarUInt32() - 1;
            }
            else
            {
                length = reader.ReadShort();
            }
            if (length < 0)
            {
                throw new Exception("non-nullable field MemberId was serialized as null");
            }
            else if (length > 0x7fff)
            {
                throw new Exception($"string field MemberId had invalid length {length}");
            }
            else
            {
                MemberId = reader.ReadString(length);
            }
        }
        if (version >= ApiVersion.Version7)
        {
            int length;
            if (version >= ApiVersion.Version8)
            {
                length = reader.ReadVarUInt32() - 1;
            }
            else
            {
                length = reader.ReadShort();
            }
            if (length < 0)
            {
                GroupInstanceId = null;
            }
            else if (length > 0x7fff)
            {
                throw new Exception($"string field GroupInstanceId had invalid length {length}");
            }
            else
            {
                GroupInstanceId = reader.ReadString(length);
            }
        }
        else
        {
            GroupInstanceId = null;
        }
        if (version <= ApiVersion.Version4)
        {
            RetentionTimeMs = reader.ReadLong();
        }
        else
        {
            RetentionTimeMs = -1;
        }
        {
            if (version >= ApiVersion.Version8)
            {
                int arrayLength;
                arrayLength = reader.ReadVarUInt32() - 1;
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Topics was serialized as null");
                }
                else
                {
                    var newCollection = new List<OffsetCommitRequestTopicMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new OffsetCommitRequestTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
            else
            {
                int arrayLength;
                arrayLength = reader.ReadInt();
                if (arrayLength < 0)
                {
                    throw new Exception("non-nullable field Topics was serialized as null");
                }
                else
                {
                    var newCollection = new List<OffsetCommitRequestTopicMessage>(arrayLength);
                    for (var i = 0; i < arrayLength; i++)
                    {
                        newCollection.Add(new OffsetCommitRequestTopicMessage(ref reader, version));
                    }
                    Topics = newCollection;
                }
            }
        }
        UnknownTaggedFields = null;
        if (version >= ApiVersion.Version8)
        {
            var numTaggedFields = reader.ReadVarUInt32();
            for (var t = 0; t < numTaggedFields; t++)
            {
                var tag = reader.ReadVarUInt32();
                var size = reader.ReadVarUInt32();
                switch (tag)
                {
                    default:
                        UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                        break;
                }
            }
        }
    }

    /// <inheritdoc />
    public void Write(ref BufferWriter writer, ApiVersion version)
    {
        var numTaggedFields = 0;
        {
            if (version >= ApiVersion.Version8)
            {
                writer.WriteCompactString(GroupId);
            }
            else
            {
                writer.WriteInt16String(GroupId);
            }
        }
        writer.WriteInt(GenerationIdOrMemberEpoch);
        {
            if (version >= ApiVersion.Version8)
            {
                writer.WriteCompactString(MemberId);
            }
            else
            {
                writer.WriteInt16String(MemberId);
            }
        }
        if (version >= ApiVersion.Version7)
        {
            if (GroupInstanceId is null)
            {
                if (version >= ApiVersion.Version8)
                {
                    writer.WriteNullableCompactString(GroupInstanceId);
                }
                else
                {
                    writer.WriteNullableInt16String(GroupInstanceId);
                }
            }
            else
            {
                if (version >= ApiVersion.Version8)
                {
                    writer.WriteCompactString(GroupInstanceId);
                }
                else
                {
                    writer.WriteInt16String(GroupInstanceId);
                }
            }
        }
        else
        {
            if (GroupInstanceId is not null)
            {
                throw new UnsupportedVersionException($"Attempted to write a non-default GroupInstanceId at version {version}");
            }
        }
        if (version <= ApiVersion.Version4)
        {
            writer.WriteLong(RetentionTimeMs);
        }
        if (version >= ApiVersion.Version8)
        {
            writer.WriteVarUInt32(Topics.Count + 1);
            foreach (var element in Topics)
            {
                element?.Write(ref writer, version);
            }
        }
        else
        {
            writer.WriteInt(Topics.Count);
            foreach (var element in Topics)
            {
                element?.Write(ref writer, version);
            }
        }
        var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
        numTaggedFields += rawWriter.FieldsCount;
        if (version >= ApiVersion.Version8)
        {
            writer.WriteVarUInt32(numTaggedFields);
            rawWriter.WriteRawTags(ref writer, int.MaxValue);
        }
        else
        {
            if (numTaggedFields > 0)
            {
                throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
            }
        }
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return ReferenceEquals(this, obj) || obj is OffsetCommitRequestMessage other && Equals(other);
    }

    /// <inheritdoc />
    public bool Equals(OffsetCommitRequestMessage? other)
    {
        if (other is null)
        {
            return false;
        }
        if (GroupId is null)
        {
            if (other.GroupId is not null)
            {
                return false;
            }
        }
        else
        {
            if (!GroupId.Equals(other.GroupId))
            {
                return false;
            }
        }
        if (GenerationIdOrMemberEpoch != other.GenerationIdOrMemberEpoch)
        {
            return false;
        }
        if (MemberId is null)
        {
            if (other.MemberId is not null)
            {
                return false;
            }
        }
        else
        {
            if (!MemberId.Equals(other.MemberId))
            {
                return false;
            }
        }
        if (GroupInstanceId is null)
        {
            if (other.GroupInstanceId is not null)
            {
                return false;
            }
        }
        else
        {
            if (!GroupInstanceId.Equals(other.GroupInstanceId))
            {
                return false;
            }
        }
        if (RetentionTimeMs != other.RetentionTimeMs)
        {
            return false;
        }
        if (Topics is null)
        {
            if (other.Topics is not null)
            {
                return false;
            }
        }
        else
        {
            if (!Topics.SequenceEqual(other.Topics))
            {
                return false;
            }
        }
        return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hashCode = 0;
        hashCode = HashCode.Combine(hashCode, GroupId, GenerationIdOrMemberEpoch, MemberId, GroupInstanceId, RetentionTimeMs, Topics);
        return hashCode;
    }

    /// <inheritdoc />
    public override string ToString()
    {
        return "OffsetCommitRequestMessage("
            + "GroupId=" + (string.IsNullOrWhiteSpace(GroupId) ? "null" : GroupId)
            + ", GenerationIdOrMemberEpoch=" + GenerationIdOrMemberEpoch
            + ", MemberId=" + (string.IsNullOrWhiteSpace(MemberId) ? "null" : MemberId)
            + ", GroupInstanceId=" + (string.IsNullOrWhiteSpace(GroupInstanceId) ? "null" : GroupInstanceId)
            + ", RetentionTimeMs=" + RetentionTimeMs
            + ", Topics=" + Topics.DeepToString()
            + ")";
    }

    /// <summary>
    /// Describes the contract for message OffsetCommitRequestTopicMessage
    /// </summary>
    internal sealed partial class OffsetCommitRequestTopicMessage: IMessage, IEquatable<OffsetCommitRequestTopicMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The topic name.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// The topic ID.
        /// </summary>
        public Guid TopicId { get; set; } = Guid.Empty;

        /// <summary>
        /// Each partition to commit offsets for.
        /// </summary>
        public List<OffsetCommitRequestPartitionMessage> Partitions { get; set; } = new ();

        /// <summary>
        /// The basic constructor of the message OffsetCommitRequestTopicMessage
        /// </summary>
        public OffsetCommitRequestTopicMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message OffsetCommitRequestTopicMessage
        /// </summary>
        public OffsetCommitRequestTopicMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version < ApiVersion.Version2 || version > ApiVersion.Version10)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of OffsetCommitRequestTopicMessage");
            }
            if (version <= ApiVersion.Version9)
            {
                int length;
                if (version >= ApiVersion.Version8)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    throw new Exception("non-nullable field Name was serialized as null");
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field Name had invalid length {length}");
                }
                else
                {
                    Name = reader.ReadString(length);
                }
            }
            else
            {
                Name = string.Empty;
            }
            if (version >= ApiVersion.Version10)
            {
                TopicId = reader.ReadGuid();
            }
            else
            {
                TopicId = Guid.Empty;
            }
            {
                if (version >= ApiVersion.Version8)
                {
                    int arrayLength;
                    arrayLength = reader.ReadVarUInt32() - 1;
                    if (arrayLength < 0)
                    {
                        throw new Exception("non-nullable field Partitions was serialized as null");
                    }
                    else
                    {
                        var newCollection = new List<OffsetCommitRequestPartitionMessage>(arrayLength);
                        for (var i = 0; i < arrayLength; i++)
                        {
                            newCollection.Add(new OffsetCommitRequestPartitionMessage(ref reader, version));
                        }
                        Partitions = newCollection;
                    }
                }
                else
                {
                    int arrayLength;
                    arrayLength = reader.ReadInt();
                    if (arrayLength < 0)
                    {
                        throw new Exception("non-nullable field Partitions was serialized as null");
                    }
                    else
                    {
                        var newCollection = new List<OffsetCommitRequestPartitionMessage>(arrayLength);
                        for (var i = 0; i < arrayLength; i++)
                        {
                            newCollection.Add(new OffsetCommitRequestPartitionMessage(ref reader, version));
                        }
                        Partitions = newCollection;
                    }
                }
            }
            UnknownTaggedFields = null;
            if (version >= ApiVersion.Version8)
            {
                var numTaggedFields = reader.ReadVarUInt32();
                for (var t = 0; t < numTaggedFields; t++)
                {
                    var tag = reader.ReadVarUInt32();
                    var size = reader.ReadVarUInt32();
                    switch (tag)
                    {
                        default:
                            UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                            break;
                    }
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            if (version <= ApiVersion.Version9)
            {
                {
                    if (version >= ApiVersion.Version8)
                    {
                        writer.WriteCompactString(Name);
                    }
                    else
                    {
                        writer.WriteInt16String(Name);
                    }
                }
            }
            if (version >= ApiVersion.Version10)
            {
                writer.WriteGuid(TopicId);
            }
            if (version >= ApiVersion.Version8)
            {
                writer.WriteVarUInt32(Partitions.Count + 1);
                foreach (var element in Partitions)
                {
                    element?.Write(ref writer, version);
                }
            }
            else
            {
                writer.WriteInt(Partitions.Count);
                foreach (var element in Partitions)
                {
                    element?.Write(ref writer, version);
                }
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            if (version >= ApiVersion.Version8)
            {
                writer.WriteVarUInt32(numTaggedFields);
                rawWriter.WriteRawTags(ref writer, int.MaxValue);
            }
            else
            {
                if (numTaggedFields > 0)
                {
                    throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
                }
            }
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is OffsetCommitRequestTopicMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(OffsetCommitRequestTopicMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (Name is null)
            {
                if (other.Name is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Name.Equals(other.Name))
                {
                    return false;
                }
            }
            if (!TopicId.Equals(other.TopicId))
            {
                return false;
            }
            if (Partitions is null)
            {
                if (other.Partitions is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!Partitions.SequenceEqual(other.Partitions))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, Name, TopicId, Partitions);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "OffsetCommitRequestTopicMessage("
                + "Name=" + (string.IsNullOrWhiteSpace(Name) ? "null" : Name)
                + ", TopicId=" + TopicId
                + ", Partitions=" + Partitions.DeepToString()
                + ")";
        }
    }

    /// <summary>
    /// Describes the contract for message OffsetCommitRequestPartitionMessage
    /// </summary>
    internal sealed partial class OffsetCommitRequestPartitionMessage: IMessage, IEquatable<OffsetCommitRequestPartitionMessage>
    {
        /// <inheritdoc />
        public List<TaggedField>? UnknownTaggedFields { get; set; } = null;

        /// <inheritdoc />
        public int IncomingBufferLength { get; private set; } = 0;

        /// <summary>
        /// The partition index.
        /// </summary>
        public int PartitionIndex { get; set; } = 0;

        /// <summary>
        /// The message offset to be committed.
        /// </summary>
        public long CommittedOffset { get; set; } = 0;

        /// <summary>
        /// The leader epoch of this partition.
        /// </summary>
        public int CommittedLeaderEpoch { get; set; } = -1;

        /// <summary>
        /// Any associated metadata the client wants to keep.
        /// </summary>
        public string CommittedMetadata { get; set; } = string.Empty;

        /// <summary>
        /// The basic constructor of the message OffsetCommitRequestPartitionMessage
        /// </summary>
        public OffsetCommitRequestPartitionMessage()
        {
        }

        /// <summary>
        /// Base constructor for deserializing message OffsetCommitRequestPartitionMessage
        /// </summary>
        public OffsetCommitRequestPartitionMessage(ref BufferReader reader, ApiVersion version)
            : this()
        {
            IncomingBufferLength = reader.Length;
            Read(ref reader, version);
        }

        /// <inheritdoc />
        public void Read(ref BufferReader reader, ApiVersion version)
        {
            if (version < ApiVersion.Version2 || version > ApiVersion.Version10)
            {
                throw new UnsupportedVersionException($"Can't read version {version} of OffsetCommitRequestPartitionMessage");
            }
            PartitionIndex = reader.ReadInt();
            CommittedOffset = reader.ReadLong();
            if (version >= ApiVersion.Version6)
            {
                CommittedLeaderEpoch = reader.ReadInt();
            }
            else
            {
                CommittedLeaderEpoch = -1;
            }
            {
                int length;
                if (version >= ApiVersion.Version8)
                {
                    length = reader.ReadVarUInt32() - 1;
                }
                else
                {
                    length = reader.ReadShort();
                }
                if (length < 0)
                {
                    CommittedMetadata = null;
                }
                else if (length > 0x7fff)
                {
                    throw new Exception($"string field CommittedMetadata had invalid length {length}");
                }
                else
                {
                    CommittedMetadata = reader.ReadString(length);
                }
            }
            UnknownTaggedFields = null;
            if (version >= ApiVersion.Version8)
            {
                var numTaggedFields = reader.ReadVarUInt32();
                for (var t = 0; t < numTaggedFields; t++)
                {
                    var tag = reader.ReadVarUInt32();
                    var size = reader.ReadVarUInt32();
                    switch (tag)
                    {
                        default:
                            UnknownTaggedFields = reader.ReadUnknownTaggedField(UnknownTaggedFields, tag, size);
                            break;
                    }
                }
            }
        }

        /// <inheritdoc />
        public void Write(ref BufferWriter writer, ApiVersion version)
        {
            var numTaggedFields = 0;
            writer.WriteInt(PartitionIndex);
            writer.WriteLong(CommittedOffset);
            if (version >= ApiVersion.Version6)
            {
                writer.WriteInt(CommittedLeaderEpoch);
            }
            if (CommittedMetadata is null)
            {
                if (version >= ApiVersion.Version8)
                {
                    writer.WriteNullableCompactString(CommittedMetadata);
                }
                else
                {
                    writer.WriteNullableInt16String(CommittedMetadata);
                }
            }
            else
            {
                if (version >= ApiVersion.Version8)
                {
                    writer.WriteCompactString(CommittedMetadata);
                }
                else
                {
                    writer.WriteInt16String(CommittedMetadata);
                }
            }
            var rawWriter = RawTaggedFieldWriter.ForFields(UnknownTaggedFields);
            numTaggedFields += rawWriter.FieldsCount;
            if (version >= ApiVersion.Version8)
            {
                writer.WriteVarUInt32(numTaggedFields);
                rawWriter.WriteRawTags(ref writer, int.MaxValue);
            }
            else
            {
                if (numTaggedFields > 0)
                {
                    throw new UnsupportedVersionException($"Tagged fields were set, but version {version} of this message does not support them.");
                }
            }
        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {
            return ReferenceEquals(this, obj) || obj is OffsetCommitRequestPartitionMessage other && Equals(other);
        }

        /// <inheritdoc />
        public bool Equals(OffsetCommitRequestPartitionMessage? other)
        {
            if (other is null)
            {
                return false;
            }
            if (PartitionIndex != other.PartitionIndex)
            {
                return false;
            }
            if (CommittedOffset != other.CommittedOffset)
            {
                return false;
            }
            if (CommittedLeaderEpoch != other.CommittedLeaderEpoch)
            {
                return false;
            }
            if (CommittedMetadata is null)
            {
                if (other.CommittedMetadata is not null)
                {
                    return false;
                }
            }
            else
            {
                if (!CommittedMetadata.Equals(other.CommittedMetadata))
                {
                    return false;
                }
            }
            return UnknownTaggedFields.CompareRawTaggedFields(other.UnknownTaggedFields);
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hashCode = 0;
            hashCode = HashCode.Combine(hashCode, PartitionIndex, CommittedOffset, CommittedLeaderEpoch, CommittedMetadata);
            return hashCode;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            return "OffsetCommitRequestPartitionMessage("
                + "PartitionIndex=" + PartitionIndex
                + ", CommittedOffset=" + CommittedOffset
                + ", CommittedLeaderEpoch=" + CommittedLeaderEpoch
                + ", CommittedMetadata=" + (string.IsNullOrWhiteSpace(CommittedMetadata) ? "null" : CommittedMetadata)
                + ")";
        }
    }
}
