version: '3.8'
services:
  kafka1:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.3.0}
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: LISTENER_EXTERNAL://:29091,CONTROLLER://kafka1:9093,LISTENER_INTERNAL://:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:SASL_PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka1:9091,LISTENER_EXTERNAL://localhost:29091'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: '${KAFKA_LOG4J_ROOT_LOGLEVEL}'
      CLUSTER_ID: '${KAFKA_CLUSTER_ID}'
      KAFKA_OPTS: ${KAFKA_OPTS}
    ports:
      - '29091:29091'
    volumes:
      - kafka1_data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka-net

  kafka2:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.3.0}
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: LISTENER_EXTERNAL://:29092,CONTROLLER://kafka2:9093,LISTENER_INTERNAL://:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:SASL_PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka2:9091,LISTENER_EXTERNAL://localhost:29092'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: '${KAFKA_LOG4J_ROOT_LOGLEVEL}'
      CLUSTER_ID: '${KAFKA_CLUSTER_ID}'
      KAFKA_OPTS: ${KAFKA_OPTS}
    ports:
      - '29092:29092'
    volumes:
      - kafka2_data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka-net

  kafka3:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.3.0}
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: LISTENER_EXTERNAL://:29093,CONTROLLER://kafka3:9093,LISTENER_INTERNAL://:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:SASL_PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka3:9091,LISTENER_EXTERNAL://localhost:29093'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: '${KAFKA_LOG4J_ROOT_LOGLEVEL}'
      CLUSTER_ID: '${KAFKA_CLUSTER_ID}'
      KAFKA_OPTS: ${KAFKA_OPTS}
    ports:
      - '29093:29093'
    volumes:
      - kafka3_data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka-net

  kafka4:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.3.0}
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 4
      KAFKA_LISTENERS: LISTENER_EXTERNAL://:29094,CONTROLLER://kafka4:9093,LISTENER_INTERNAL://:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:SASL_PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka4:9091,LISTENER_EXTERNAL://localhost:29094'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: '${KAFKA_LOG4J_ROOT_LOGLEVEL}'
      CLUSTER_ID: '${KAFKA_CLUSTER_ID}'
      KAFKA_OPTS: ${KAFKA_OPTS}
    ports:
      - '29094:29094'
    volumes:
      - kafka4_data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka-net

  kafka5:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.3.0}
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 5
      KAFKA_LISTENERS: LISTENER_EXTERNAL://:29095,CONTROLLER://kafka5:9093,LISTENER_INTERNAL://:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:SASL_PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka5:9091,LISTENER_EXTERNAL://localhost:29095'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093,5@kafka5:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: '${KAFKA_LOG4J_ROOT_LOGLEVEL}'
      CLUSTER_ID: '${KAFKA_CLUSTER_ID}'
      KAFKA_OPTS: ${KAFKA_OPTS}
    ports:
      - '29095:29095'
    volumes:
      - kafka5_data:/var/lib/kafka/data
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka-net

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  kafka4_data:
  kafka5_data:

networks:
  kafka-net:
    driver: bridge