version: '3.9'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION:-7.0.0}'
    restart: always
    ports:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - kafka-network
 
  broker:
    image: 'confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.0.0}'
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENERS: 'LISTENER_INTERNAL://:9091,LISTENER_LOCAL://:29091'
      KAFKA_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:9092'
#      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: '${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '2'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: '3000'
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: '3000'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_ROOT_LOGLEVEL: '${KAFKA_LOG4J_ROOT_LOGLEVEL}'
    networks:
      - kafka-network

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    hostname: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge