//92-E3-D8-6F-E1-DD-5B-44-BB-37-15-76-9C-69-62-A3-E4-9D-DD-E9-A4-E1-8A-7B-7E-15-9B-7D-4B-1A-C7-BF
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Messages;
using NKafka.Protocol;
using Xunit;

namespace NKafka.Tests.Messages;

public sealed partial class DeleteTopicsRequestMessageTests
{

    [Fact(DisplayName = "Check serialize and deserialize 'DeleteTopicsRequestMessage' message by Version1")]
    public void SerializeAndDeserializeMessage_ApiVersion1_Success()
    {
        var message = new DeleteTopicsRequestMessage
        {
            TopicNames = new (),
            TimeoutMs = -420004200,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version1);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DeleteTopicsRequestMessage' message by Version2")]
    public void SerializeAndDeserializeMessage_ApiVersion2_Success()
    {
        var message = new DeleteTopicsRequestMessage
        {
            TopicNames = new (),
            TimeoutMs = -420004200,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version2);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DeleteTopicsRequestMessage' message by Version3")]
    public void SerializeAndDeserializeMessage_ApiVersion3_Success()
    {
        var message = new DeleteTopicsRequestMessage
        {
            TopicNames = new (),
            TimeoutMs = -420004200,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version3);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DeleteTopicsRequestMessage' message by Version4")]
    public void SerializeAndDeserializeMessage_ApiVersion4_Success()
    {
        var message = new DeleteTopicsRequestMessage
        {
            TopicNames = new (),
            TimeoutMs = -420004200,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version4);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DeleteTopicsRequestMessage' message by Version5")]
    public void SerializeAndDeserializeMessage_ApiVersion5_Success()
    {
        var message = new DeleteTopicsRequestMessage
        {
            TopicNames = new (),
            TimeoutMs = -420004200,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version5);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DeleteTopicsRequestMessage' message by Version6")]
    public void SerializeAndDeserializeMessage_ApiVersion6_Success()
    {
        var message = new DeleteTopicsRequestMessage
        {
            Topics = new (),
            TimeoutMs = -420004200,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version6);
    }
}
