//38-0A-E2-87-49-93-68-53-90-7E-92-CE-5A-0F-C1-58-3A-A6-32-EB-97-03-5E-3B-D2-01-35-9C-11-95-71-88
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Messages;
using NKafka.Protocol;
using Xunit;

namespace NKafka.Tests.Messages;

public sealed partial class DescribeAclsRequestMessageTests
{

    [Fact(DisplayName = "Check serialize and deserialize 'DescribeAclsRequestMessage' message by Version1")]
    public void SerializeAndDeserializeMessage_ApiVersion1_Success()
    {
        var message = new DescribeAclsRequestMessage
        {
            ResourceTypeFilter = 42,
            ResourceNameFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            PatternTypeFilter = 42,
            PrincipalFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            HostFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            Operation = 42,
            PermissionType = 42,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version1);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DescribeAclsRequestMessage' message by Version2")]
    public void SerializeAndDeserializeMessage_ApiVersion2_Success()
    {
        var message = new DescribeAclsRequestMessage
        {
            ResourceTypeFilter = 42,
            ResourceNameFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            PatternTypeFilter = 42,
            PrincipalFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            HostFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            Operation = 42,
            PermissionType = 42,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version2);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'DescribeAclsRequestMessage' message by Version3")]
    public void SerializeAndDeserializeMessage_ApiVersion3_Success()
    {
        var message = new DescribeAclsRequestMessage
        {
            ResourceTypeFilter = 42,
            ResourceNameFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            PatternTypeFilter = 42,
            PrincipalFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            HostFilter = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            Operation = 42,
            PermissionType = 42,
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version3);
    }
}
