//5E-61-C9-42-3B-75-6B-5A-4E-83-A4-45-BE-86-CC-51-63-EF-32-8E-5E-9D-15-86-F6-0F-09-89-B7-0B-B8-23
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Messages;
using NKafka.Protocol;
using Xunit;

namespace NKafka.Tests.Messages;

public sealed partial class FetchRequestMessageTests
{

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version4")]
    public void SerializeAndDeserializeMessage_ApiVersion4_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version4);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version5")]
    public void SerializeAndDeserializeMessage_ApiVersion5_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version5);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version6")]
    public void SerializeAndDeserializeMessage_ApiVersion6_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version6);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version7")]
    public void SerializeAndDeserializeMessage_ApiVersion7_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version7);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version8")]
    public void SerializeAndDeserializeMessage_ApiVersion8_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version8);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version9")]
    public void SerializeAndDeserializeMessage_ApiVersion9_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version9);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version10")]
    public void SerializeAndDeserializeMessage_ApiVersion10_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version10);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version11")]
    public void SerializeAndDeserializeMessage_ApiVersion11_Success()
    {
        var message = new FetchRequestMessage
        {
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version11);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version12")]
    public void SerializeAndDeserializeMessage_ApiVersion12_Success()
    {
        var message = new FetchRequestMessage
        {
            ClusterId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version12);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version13")]
    public void SerializeAndDeserializeMessage_ApiVersion13_Success()
    {
        var message = new FetchRequestMessage
        {
            ClusterId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version13);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version14")]
    public void SerializeAndDeserializeMessage_ApiVersion14_Success()
    {
        var message = new FetchRequestMessage
        {
            ClusterId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            ReplicaId = -420004200,
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version14);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version15")]
    public void SerializeAndDeserializeMessage_ApiVersion15_Success()
    {
        var message = new FetchRequestMessage
        {
            ClusterId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            ReplicaState = new (),
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version15);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version16")]
    public void SerializeAndDeserializeMessage_ApiVersion16_Success()
    {
        var message = new FetchRequestMessage
        {
            ClusterId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            ReplicaState = new (),
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version16);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'FetchRequestMessage' message by Version17")]
    public void SerializeAndDeserializeMessage_ApiVersion17_Success()
    {
        var message = new FetchRequestMessage
        {
            ClusterId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            ReplicaState = new (),
            MaxWaitMs = -420004200,
            MinBytes = -420004200,
            MaxBytes = -420004200,
            IsolationLevel = 42,
            SessionId = -420004200,
            SessionEpoch = -420004200,
            Topics = new (),
            ForgottenTopicsData = new (),
            RackId = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version17);
    }
}
