//38-AC-2B-AF-8A-8A-64-08-D8-17-43-9C-B7-10-66-B7-86-97-25-A8-D0-F6-75-95-7E-70-F3-66-E2-0F-57-C6
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Messages;
using NKafka.Protocol;
using Xunit;

namespace NKafka.Tests.Messages;

public sealed partial class OffsetForLeaderEpochResponseMessageTests
{
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochResponseMessage' message by Version0")]
    public void SerializeAndDeserializeMessage_ApiVersion0_Success()
    {
        var message = new OffsetForLeaderEpochResponseMessage
        {
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version0);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochResponseMessage' message by Version1")]
    public void SerializeAndDeserializeMessage_ApiVersion1_Success()
    {
        var message = new OffsetForLeaderEpochResponseMessage
        {
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version1);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochResponseMessage' message by Version2")]
    public void SerializeAndDeserializeMessage_ApiVersion2_Success()
    {
        var message = new OffsetForLeaderEpochResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version2);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochResponseMessage' message by Version3")]
    public void SerializeAndDeserializeMessage_ApiVersion3_Success()
    {
        var message = new OffsetForLeaderEpochResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version3);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochResponseMessage' message by Version4")]
    public void SerializeAndDeserializeMessage_ApiVersion4_Success()
    {
        var message = new OffsetForLeaderEpochResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version4);
    }
}
