//9E-DC-D5-6E-E0-C8-B4-34-14-98-60-A2-87-6B-06-B7-F8-82-4A-62-FD-B2-7D-F2-8A-1C-78-D8-5C-89-B6-76
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Messages;
using NKafka.Protocol;
using Xunit;

namespace NKafka.Tests.Messages;

public sealed partial class OffsetCommitResponseMessageTests
{

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version2")]
    public void SerializeAndDeserializeMessage_ApiVersion2_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version2);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version3")]
    public void SerializeAndDeserializeMessage_ApiVersion3_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version3);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version4")]
    public void SerializeAndDeserializeMessage_ApiVersion4_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version4);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version5")]
    public void SerializeAndDeserializeMessage_ApiVersion5_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version5);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version6")]
    public void SerializeAndDeserializeMessage_ApiVersion6_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version6);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version7")]
    public void SerializeAndDeserializeMessage_ApiVersion7_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version7);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version8")]
    public void SerializeAndDeserializeMessage_ApiVersion8_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version8);
    }

    [Fact(DisplayName = "Check serialize and deserialize 'OffsetCommitResponseMessage' message by Version9")]
    public void SerializeAndDeserializeMessage_ApiVersion9_Success()
    {
        var message = new OffsetCommitResponseMessage
        {
            ThrottleTimeMs = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version9);
    }
}
