//65-69-27-BD-39-33-2E-9A-67-4B-2B-46-27-A2-69-D1-F7-C4-6D-A3-20-4E-7B-AF-C1-63-6D-33-38-6B-4A-F1
//  This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// 
//  PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com
// 
//  Copyright ©  2022 Aleksey Kalduzov. All rights reserved
// 
//  Author: Aleksey Kalduzov
//  Email: alexei.kalduzov@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      https://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// <auto-generated> THIS CODE IS AUTOMATICALLY GENERATED.  DO NOT EDIT. </auto-generated>

// ReSharper disable RedundantUsingDirective
// ReSharper disable UnusedType.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable PartialTypeWithSinglePart

#nullable enable

using NKafka.Messages;
using NKafka.Protocol;
using Xunit;

namespace NKafka.Tests.Messages;

public sealed partial class OffsetForLeaderEpochRequestMessageTests
{
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochRequestMessage' message by Version0")]
    public void SerializeAndDeserializeMessage_ApiVersion0_Success()
    {
        var message = new OffsetForLeaderEpochRequestMessage
        {
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version0);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochRequestMessage' message by Version1")]
    public void SerializeAndDeserializeMessage_ApiVersion1_Success()
    {
        var message = new OffsetForLeaderEpochRequestMessage
        {
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version1);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochRequestMessage' message by Version2")]
    public void SerializeAndDeserializeMessage_ApiVersion2_Success()
    {
        var message = new OffsetForLeaderEpochRequestMessage
        {
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version2);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochRequestMessage' message by Version3")]
    public void SerializeAndDeserializeMessage_ApiVersion3_Success()
    {
        var message = new OffsetForLeaderEpochRequestMessage
        {
            ReplicaId = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version3);
    }
    [Fact(DisplayName = "Check serialize and deserialize 'OffsetForLeaderEpochRequestMessage' message by Version4")]
    public void SerializeAndDeserializeMessage_ApiVersion4_Success()
    {
        var message = new OffsetForLeaderEpochRequestMessage
        {
            ReplicaId = -420004200,
            Topics = new (),
        };
        message.SerializeAndDeserializeMessageTest(ApiVersion.Version4);
    }
}
